### ISSUE TITLE
Support @@locale

### ISSUE THREAD

**Issue by donny-dont** [dart-lang/intl#100]
The specification seems to use `"@@locale": "en_GB"` while intl does `"_locale": "en_BG"`

See https://github.com/alan-knight/polymer_intl/issues/1 as well

**Comment by alan-knight** [comment]
... and I just found the bit in the code where if locale is missing it tries to figure it out from the file name. So that's what you were seeing before.

**Comment by donny-dont** [comment]
Ah cool thanks for finding that. Maybe a warning during generation that a locale wasn't found and what the resolution should be?

**Comment by alan-knight** [comment]
@@locale and a message when it gets it from the file name both in 0.12.6
