### ISSUE TITLE
intl has too many dependencies

### ISSUE THREAD

**Issue by abarth** [dart-lang/intl#107]
The intl package doesn't cleanly separate the dependencies that are needed at development time from those that are needed in production.

When I depend on package:intl, the following gets pulled into my project:

```
|-- intl 0.12.7
|   |-- analyzer 0.27.1+2
|   |   |-- args...
|   |   |-- path...
|   |   |-- glob 1.1.0
|   |   |   |-- collection...
|   |   |   |-- path...
|   |   |   '-- string_scanner...
|   |   |-- html 0.12.2+1
|   |   |   |-- source_span...
|   |   |   |-- csslib 0.12.2
|   |   |   |   |-- args...
|   |   |   |   |-- path...
|   |   |   |   |-- source_span...
|   |   |   |   '-- logging 0.11.2
|   |   |   '-- utf 0.9.0+2
|   |   |-- package_config 0.1.3
|   |   |   |-- path...
|   |   |   '-- charcode 1.1.0
|   |   |-- plugin 0.1.0
|   |   |-- watcher 0.9.7
|   |   |   '-- path...
|   |   '-- yaml 2.1.8
|   |       |-- charcode...
|   |       |-- collection...
|   |       |-- source_span 1.2.1
|   |       |   '-- path...
|   |       '-- string_scanner 0.1.4+1
|   |           |-- charcode...
|   |           '-- source_span...
|   |-- args 0.13.3+3
|   |-- path 1.3.9
|   '-- petitparser 1.5.1
```

However, I don't believe I need package:analyzer, for example, in production.

We should split the intl package into two pieces, one that has the code needed in production and another that has the tools for producing the artifacts needed in production.

**Comment by alan-knight** [comment]
That seems reasonable enough, although a breaking change for all users. I don't think having those as dev dependencies would work. What are the negative consequences of having these extra things included in the list of packages?

**Comment by abarth** [comment]
> What are the negative consequences of having these extra things included in the list of packages?

Including these non-production dependencies in my production code has several negative consequences:

1. Every additional dependency adds complexity for compliance.  For example, we need to validate that we have the appropriate license for all transitive dependencies that we use in production.

2. Every additional dependency slows down the onboarding process for new users because pub needs to analyze the dependency structure and download the code from the network, which can quite slow in non-US countries.

3. Every additional dependency constraints the space of available versions of those packages for downstream developers.

4. In our particular case, we will eventually pin all of our transitive dependencies to exact versions so that we can be confident that our package works exactly the same way for end-developers as it works in our testing lab, exacerbating problem (3).

**Comment by alan-knight** [comment]
0.14.0 moves all the dependencies to intl_translation.

**Comment by abarth** [comment]
Thanks so much!
