### ISSUE TITLE
Check validity of Dart input files

### ISSUE THREAD

**Issue by alan-knight** [dart-lang/intl#109]
It's easy to make the mistake of running generate_from_arb with the input of the generated Dart files from a previous run instead of the original source files, and very hard to figure out why it just deletes all the translations. We should verify that and give a useful error message. The most obvious way is that if there's overlap between inputs and outputs that's an error. A more sophisticated mechanism would be to recognize the generated code, or even if we noticed that the set of messages for translation from the source code was completely empty.  @devoncarew

**Comment by devoncarew** [comment]
Also, I think just slightly more verbose help from the generate_from_arb command would have helped me here. And or perhaps an example for how to use it?

The usage package supports things like a `usageFooter` - that could be a place to put an example.

**Comment by alan-knight** [comment]
Good idea, thanks.

**Comment by mosuem** [comment]
Closing in favor of #110 .
