### ISSUE TITLE
strong mode runtime errors in src/date_format_internal.dart

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/intl#116]
Strong mode infers the type on `dateTimeSymbols` and `dateTimePatterns` as `UninitializedLocaleData`.  When it's actually set to a different type (a `HashMap`?) in the initialization code below, we get a runtime error in DDC:

https://github.com/dart-lang/intl/blob/master/lib/src/date_format_internal.dart

**Comment by alan-knight** [comment]
This seems like been fixed or a lot of things wouldn't be working with DDC.
