### ISSUE TITLE
intl/build/test/date_time_format_http_request_test failing on browsers

### ISSUE THREAD

**Issue by whesse** [dart-lang/intl#121]
Since the change to testing the package using --no-packages-directory, this test has started failing on browsers running dart2js.  The error can be seen on https://build.chromium.org/p/client.dart.packages/builders/packages-linux-intl
Please ignore the Dartium failures - that is due to a problem in the testing scripts.
The failures on chrome and ff seem to be real though.  I haven't tried to reproduce them locally.

```
                        <td class="unittest-fail">
                          FAIL
                        </td>
                        <td>
                          <p>Expectation: 
                            <a href="#testFilter=Initializing a locale that needs fallback">
                              Initializing a locale that needs fallback
                            </a>.
                          </p>
                          <pre>Caught Instance of 'ProgressEvent'</pre>
                        </td>
                      </tr>      <tr>
                        <td>2</td>
                        <td class="unittest-error">
                          ERROR
                        </td>
                        <td>
                          <p>Expectation: 
                            <a href="#testFilter=Multiple patterns">
                              Multiple patterns
                            </a>.
                          </p>
                          <pre>Setup failed: Caught Instance of 'ProgressEvent'</pre>
                        </td>
                      </tr>      <tr>
                        <td>3</td>
```

**Comment by whesse** [comment]
This does not reproduce locally.  I can try harder to reproduce locally, repeating exactly the steps the builder runs.  Doesn't look to me like a 1.19 blocker.

Note that we want to stop using test.dart on packages, in favor of package:test.  But package:test doesn't work on this, perhaps because it uses unittest.  Filing a separate issue.

**Comment by alan-knight** [comment]
It seems like this is likely obsolete. Intl has been converted to use package:test, and the infrastructure has changed. I don't see any suppression for this, so I'm guessing it's OK. If not, please re-open.
