### ISSUE TITLE
Parsing two-digit year `16` with results in `0016` and not `2016`

### ISSUE THREAD

**Issue by DanTup** [dart-lang/intl#123]
``` dart
import 'package:intl/intl.dart';
final dateFormat = new DateFormat("d/M/y H:m:s");
print(dateFormat.parse("01/02/16 12:11:12").year);
```

This code results in a year of `0016` and not `2016`. Same thing happens whether I use `y` or `yy` in the format. Unfortunately it's tricky to fix this, because you can't even `.add` 2000 years, because the Duration class only goes up to days!

Other languages make assumptions about two-digit years being 19/20; it probably makes sense to do the same.

**Comment by andrewmcdnz** [comment]
Nearly 3 years later I've stumbled across the same issue via the unit tests in my Flutter app. The issue occurs even when using the specific example from the comments in date_format.dart (pattern: "MM/dd/yy", input "01/11/12" ; the resulting year is 0012). This contradicts in the description in date_format.dart (line 202) which states it should resolve to 2012. Needs to be fixed.

**Comment by altherat** [comment]
A hacky workaround by adding Duration could be:

```
dateFormat.parse('01/02/16 12:11:12').add(Duration(milliseconds: DateTime(1970 + 2000).millisecondsSinceEpoch));
```

**Comment by jamesderlin** [comment]
@altherat That hacky workaround isn't correct since it will change the time. (That is, adding 24 * 60 * 60 seconds to a date might not necessarily be the same as incrementing the day by 1 due to leap seconds, daylight saving, ...).  You'd be better off taking the result of `DateFormat.parse` and constructing a new `DateTime` with an adjusted year.

**Comment by johnneijzen** [comment]
@jamesderlin that would problem but they did not fixed bug for 4 years already the closest to fixed is #125 but it got rejected

**Comment by harlandgomez** [comment]
I think @jamesderlin was right all along. I used the hacky workaround and after sometime it was giving me a wrong month. So I switched back to adding 2000 in the year as in  var year = (dateFormat.parse("01/02/16 12:11:12").year + 2000)..

**Comment by jamesderlin** [comment]
> I think @jamesderlin was right all along. I used the hacky workaround and after sometime it was giving me a wrong month. So I switched back to adding 2000 in the year as in `var year = (dateFormat.parse("01/02/16 12:11:12").year + 2000)`..

Please do **not** unconditionally add 2000.  As I mentioned, such hacks will break when this bug is fixed.  Add 2000 *only* to 2-digit years.

And yes, a fix is forthcoming.

**Comment by harlandgomez** [comment]
@jamesderlin, i was just showing how to simply add 2000, of course, there are checks before it arrives to that..

**Comment by jamesderlin** [comment]
> @jamesderlin, i was just showing how to simply add 2000, of course, there are checks before it arrives to that..

Okay, I just don't want people to copy-and-paste that workaround blindly.  I have seen other people also suggest workarounds that omit any checks.

**Comment by harlandgomez** [comment]
Understood, simple check can be?
```
    final twoDigitYear = dateFormat.parse("01/02/16 12:11:12").year;
    if(0 <= twoDigitYear && twoDigitYear <= 99){
      year = (twoDigitYear + 2000);
      //..
    }
```

**Comment by jamesderlin** [comment]
This is now fixed on `master` by b1335afc2e72cce096c78aa3b600e8b8424631ab.

**Comment by bsneider** [comment]
@jamesderlin  when will 17.0 show up on pub.dev? 
<img width="1073" alt="Screen Shot 2020-06-07 at 1 31 39 PM" src="https://user-images.githubusercontent.com/54788551/83977025-77c96d80-a8c3-11ea-861d-e5fabd72b477.png">

**Comment by jamesderlin** [comment]
0.17 probably will not be available on pub.dev until `package:intl` is updated for NNBD.  We're treating this fix as a breaking change.  Changes for NNBD are also expected to be breaking, and we'd like to avoid publishing multiple breaking versions in a short timespan.  I don't know what the timeline is.

In the meantime, yes, you can have your [`pubspec.yaml` file point to the GitHub repository](https://dart.dev/tools/pub/dependencies#git-packages).

**Comment by jamesderlin** [comment]
A prerelease version of 0.17 is now available.
