### ISSUE TITLE
Pasring huge double values 

### ISSUE THREAD

**Issue by VitaliLiashchuk** [dart-lang/intl#127]
Hi guys,
    I found that intl works incorrectly with huge double values. Here are an example:
var f = new NumberFormat("###.0#", "en_US");
var result = f.format(250716241879130000.0);

result contains "250716241879129984.0"

I think it happens because it tries convert value to int instead use double.

**Comment by zoechi** [comment]
Dart in the browser doesn't distinguish between int and double.
https://dartpad.dartlang.org/9bab4e08dd83c624516bf92075da4fd3
If you need exact representation you should not rely on `double` but instead use something like https://pub.dartlang.org/packages/decimal

**Comment by alan-knight** [comment]
This isn't in the browser. It does seem like a bug, but a VM one, that 

250716241879130000.0.toInt() = 250716241879129984

when we can in fact represent that integer. It seems like toInt() is always converting to a limited precision representation? @a-siva

**Comment by rakudrama** [comment]
There is no bug here. __double__ is the wrong data type for the job.

__double__ is the wrong data type if you have values that have more than 16 significant digits, or where you require arithmetic without rounding errors (see e.g. http://floating-point-gui.de/)

250716241879130000.0 is outside the range where a IEEE-754 64-bit double can represent consecutive integers.
You can see this:

    print(250716241879130000.0 + 1 == 250716241879130000.0);  // true

In fact, there is _no_ double that represents the value 250716241879130000.0 exactly.
When that is parsed, it is converted to the nearest number that can be represented by a double.
The nearest doubles are

```
    250716241879129952.0
    250716241879129984.0
    250716241879130020.0
```

__double__ cannot represent numbers between these values.

There are many numbers that map on to 250716241879129984.0

250716241879130000.0 and
250716241879130000.000001 and
250716241879130001.0

are all closer to 250716241879129984.0 that the other two nearest numbers, so all are mapped to 250716241879129984.0

If you print those numbers, you get the shortest decimal value that maps to the same representation (we ignore trailing zeroes in the 'shortest'). There are an infinite number of inputs that could map to a given double value, but the shortest one is unique.

```dart
    print(250716241879129952.0);  // 250716241879129950.0
    print(250716241879129984.0);  // 250716241879130000.0
    print(250716241879130020.0);  // 250716241879130020.0
```

This might have given the illusion that 250716241879130000.0 can be represented exactly, but you already has the 'wrong' value.
