### ISSUE TITLE
Support deferred loading/tree-shaking of non-message data

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/intl#130]
Otherwise you get big payloads when you just want text internationalized.

**Comment by alan-knight** [comment]
Could you be more specific about which data you're interested in?

**Comment by matanlurey** [comment]
I guess I'm just asking for a way to use pkg/intl without the intl data bundles.

(I've also noticed they've started to get integrated directly in newer browsers)

**Comment by alan-knight** [comment]
You don't have to include the data bundles. But you won't be able to do a lot of internationalization without them. What is it you want to use it for?
