### ISSUE TITLE
FormatException: Could not find an option named "generated_file_prefix"

### ISSUE THREAD

**Issue by Tomucha** [dart-lang/intl#132]
I'm following the example here:  https://pub.dartlang.org/packages/intl_translation

And after:

       pub run intl_translation:generate_from_arb --generated_file_prefix=fnx `find lib -name *.dart` translations/*

I recieve: FormatException: Could not find an option named "generated_file_prefix".

Correct option name is "generated-file-prefix" (dashes not underscores).

Both error message AND documentation are probably incorrect.

**Comment by alan-knight** [comment]
Thanks.

Fix pending for the documentation.  I'm not sure what you mean about the error message. It's just using the args package.

**Comment by Tomucha** [comment]
By error message I mean: *FormatException: Could not find an option named "generated_file_prefix".*

... again - incorrect name of the parameter (with underscores).

**Comment by alan-knight** [comment]
In that case it's not incorrect. It's just repeating the option name you provided and saying it couldn't find it. For comparison, try running

      pub run intl_translation:generate_from_arb --anything_that_does_not_exist_as_an_option

**Comment by alan-knight** [comment]
It would be nice if args did something like what git does, where if you type something that's close to an option that does exist it suggests it, but I don't think that's available at the moment.

The docs error is fixed in https://github.com/dart-lang/intl_translation/commit/377aa3a526ebe0ca7aeb2eb4d2206fe2dd5f6fde

**Comment by Tomucha** [comment]
Ok. Combination with the typo in the documentation was deadly.
Thanks!

**Comment by Cge001** [comment]
flutter pub run intl_translation:generate_from_arb lib/src/i10n/localization_intl.dart lib/i10n-arb/intl_*.arb

i use this to generate all *.dart files by every arb. is Effective！
