### ISSUE TITLE
Referring to package:path without explicit dependency ?

### ISSUE THREAD

**Issue by dam0vm3nt** [dart-lang/intl#134]
Is it correcto to have a reference to `package:path` [here](https://github.com/dart-lang/intl/blob/master/lib/date_symbol_data_file.dart#L12) without any dependency for `path` in `pubspec.yaml` ?

**Comment by alan-knight** [comment]
No, it doesn't.

**Comment by alan-knight** [comment]
I think it got removed when intl_translation was split out and not noticed because people aren't generally using the file loading mechanism.

**Comment by dam0vm3nt** [comment]
k, thanks.
I got stuck into this when trying to build it with ddc...
