### ISSUE TITLE
Use the mirror system to find the package directory in data_directory

### ISSUE THREAD

**Issue by alan-knight** [dart-lang/intl#138]
The dart_style package uses the mirror system to find the directory, which may be better than the hacky way we're doing it now, particularly with package:test, where we don't get the script as a path, but as a data URL. See, e.g. https://www.google.com/url?sa=D&q=https%3A%2F%2Fgithub.com%2Fdart-lang%2Fdart_style%2Fblob%2Fmaster%2Ftest%2Futils.dart%23L24

**Comment by rakudrama** [comment]
So long as this is only for testing.
Avoid `import 'dart:mirrors';` in apps deployed with dart2js

**Comment by alan-knight** [comment]
This has been improved enough to work fine with package:test in b6ced6c9d7244d07567cd5c36b0c1db562c45062 so I think it's adequate unless another issue comes up.
