### ISSUE TITLE
Clean up plural handling of ONE vs. =1, easier way to include the howMany parameter

### ISSUE THREAD

**Issue by alan-knight** [dart-lang/intl#139]
ICU plurals have two separate cases for =1 and ONE, where the former means precisely 1 and the second is anything singular, e.g. 21 in Russian. And =0 is similar.

Right now we have only a "one" named parameter on Intl.plural. This is by default emitted as an =1 into the translation file, but is used for any singular case. So there are a couple of issues.
  - Provide the ability to specify both. But we can't use "1" or "=1" as a parameter name, so a good name is tricky.
  - Backward compatibility for existing messages.
  - Fix up documentation - in particular messages of the ONE form should include the howMany parameter in the text.

Related to this is that using the howMany parameter is awkward. If you just use it directly in an interpolation then it just uses the toString(), it's not formatted according to the locale rules. Since it's an integer and typically small this is usually not too bad. But for locales using non-Latin digits it will be a problem. And for large numbers the grouping separators will be wrong.  Imagine a "There are 1.234 new messages"

It's possible we could do some magic where Intl.plural does the formatting and passes the string as an extra parameter, and generates corresponding code. That wouldn't work for the non-generated case, but if we assume without loss of generality that developers are fine with en_US formatting it might not be too bad. e.g.
e.g.
plural(howMany, a, b, c, ...) {
  var formattedHowMany = ...
  return _plural(howMany, formattedHowMany, a, b, c);
}

Or alternatively we treat it like we do select with enums, where we always get the string format of the parameter and use that to match. It would mean that the plural logic for choosing would have to work with the locale-specific format, which is ugly, but less intrusive in code generation and it would work uniformly.

**Comment by alan-knight** [comment]
I have a clever plan, which may even work.

I think we can generate code in the translations that will format the number as a string and use that as the parameter, but pass the number down to the selection logic. In the non-translated fallback case you can just interpolate the parameter, and it will print as an integer in the default locale. If we assume that's US English <large grin> or at least that the number formatting of int.toString() matches the developer's locale, then that will work. And even in the case of a fallback translation it will do it properly. Something like

```
foo(n, other) => Intl.plural(n, one: 'There are $n', ...

... and in generated code...

m123(somePrivateName, other) {
   var n = formatCorrectlyForLocale(somePrivateName);
   return Intl.plural(somePrivateName, one: 'There are $n', ...
} 
```

So we don't modify the user's strings or variable names. They still interpolate the variable 'n', it just isn't the original parameter in the generated code.

**Comment by mosuem** [comment]
Closing in favor of #411 .
