### ISSUE TITLE
Intl.select does not document that examples should be const

### ISSUE THREAD

**Issue by dgrove** [dart-lang/intl#140]
(Originally filed as https://github.com/dart-lang/sdk/issues/29864 )
The Intl.message documentation specifies that the examples parameter must be a const literal map. Intl.select has an examples parameter which is forwarded to a call to Intl.message, but there is no documentation for Intl.select that indicates that it must be const.

See also: https://github.com/dart-lang/sdk/issues/29381 .

**Comment by alan-knight** [comment]
@leafpetersen  Which documentation are you looking at? Just general dartdocs?
I believe that dart2js will optimize those maps away completely, but that still leaves an issue at development. I think we could also possibly enforce that they need to be const.

**Comment by leafpetersen** [comment]
docs are here:

https://www.dartdocs.org/documentation/intl/0.14.0/intl/Intl/message.html
https://www.dartdocs.org/documentation/intl/0.14.0/intl/Intl/select.html

The issue filed by @rakudrama ( dart-lang/sdk#29381 ) suggests that dart2js isn't eliminating them universally.

**Comment by leafpetersen** [comment]
I don't have strong opinions about whether that comment should or should not be in the docs - just struck me as incoherent when reading them that examples was documented as "must be const" in one, but not in the other.

**Comment by rakudrama** [comment]
dart2js will not remove map literals unless they are const.
In the general case the maps cannot be removed since the construction could throw.
We could make dart2js smarter and remove map literals where by some heuristics we know there will be no exception. This will not help DDC, but using const maps might help DDC.

**Comment by alan-knight** [comment]
As of **https://github.com/dart-lang/intl_translation/commit/b3d3a894c9f897a6327d463d56d6272d52de9b41** intl_translation enforces that examples must be const.
