### ISSUE TITLE
Add "ps" and "sd" locales

### ISSUE THREAD

**Issue by yjbanov** [dart-lang/intl#144]
Locales "ps" and "sd", which are supported by Flutter, are missing in `date_symbol_data_local.dart`.

**Comment by alan-knight** [comment]
Very good timing. I have a CL in flight to update the data and add a couple of locales.

**Comment by alan-knight** [comment]
However, note that http://demo.icu-project.org/icu-bin/locexp?d_=en&_=sd says at the top
"Note: You're viewing a locale that does not have verified data . ICU will support this with inherited information, but that information is not verified to be correct. [Sindhi] "

**Comment by yjbanov** [comment]
@HansMuller, how do we verify our "sd" data in Flutter? Can we use the same process here?

**Comment by alan-knight** [comment]
In fact, it appears that there is no date symbol data for sd in CLDR 31.0.1. This starts to seem infeasible for "sd".

**Comment by alan-knight** [comment]
"ps" is added in 0f069dc55ec941a925107388641086ec44c554cf 
We can't easily add "sd" until it's supported in CLDR. But see also 8754d3832027b7dcff582c57b2bbdee68c576772 which lets you add it yourself more easily. But I'm curious where you'd be getting the data from.

**Comment by yjbanov** [comment]
Thanks. I'll temporarily remove support for "sd" in Flutter due to unreliable data.

**Comment by Omi231** [comment]
@alan-knight @yjbanov  Sindhi is the mother tongue of 50 million people worldwide. Its a shame it is not supported in flutter.

**Comment by mosuem** [comment]
Sindhi is indeed supported now, tracking the progress of adding it in #525.
