### ISSUE TITLE
Make initializeDateSymbols and initializeDatePatterns public

### ISSUE THREAD

**Issue by yjbanov** [dart-lang/intl#145]
In Flutter we'd like to customize how we load date data. Specifically:

- we'd like to limit the available locales to the supported ones
- we'd like to be able to add missing locale data (e.g. `sd`)
- we'd like to be able to load data _synchronously_

**Comment by alan-knight** [comment]
Fixed in 8754d3832027b7dcff582c57b2bbdee68c576772
