### ISSUE TITLE
no static method initializeMessages in intl package

### ISSUE THREAD

**Issue by Fandekasp** [dart-lang/intl#153]
Can you have a look at [the issue I raised in the flutter repo](https://github.com/flutter/flutter/issues/13121) ? Wondering if their example using intl is correct or not...

Looking [at your code](https://github.com/dart-lang/intl/search?utf8=%E2%9C%93&q=initializeMessages&type=), I can't figure out where does this `initializeMessages` even come from, this is quite magic! Can someone enlighten me on this operation ?

**Comment by alan-knight** [comment]
It's generated when you run e.g. https://github.com/dart-lang/intl_translation/blob/master/bin/generate_from_arb.dart 

See https://github.com/dart-lang/intl#extracting-and-using-translated-messages
