### ISSUE TITLE
Make it easier to add missing locales for date formats (e.g. en_NZ)

### ISSUE THREAD

**Issue by srtonz** [dart-lang/intl#155]
I noticed that the date format for `en_NZ` is completely missing from the package and dates are formatted incorrectly on devices set to `en_NZ`. For now I can use `en_GB` or `en_AU` as a workaround, but it took a while to figure out what was going on.

Couldn't find a simple way of adding a new locale definition myself, so opening this as an issue. There might be other missing locales as well?

**Comment by alan-knight** [comment]
The locale data is generated and we just use the same locale set as Closure, so it's not so easy to add one. But it ought to be easier than it is to add one within an application. Changing the name to represent that.

The fact that "en" uses a convention only used in the US seems like a bug, but also one more general than this library :-(

**Comment by wilburt** [comment]
Please, is there any update on this? `en_NG` is missing too and it is not very convenient to fallback to `en_GB` for proper date formats.

**Comment by diegoveloper** [comment]
any update about this ?

**Comment by pavanvora** [comment]
Any update on this issue?

**Comment by alan-knight** [comment]
While it should be easier to do this in a nice way, it's not that difficult to do with one `src` import that's been stable for a very long time. e.g. 

I don't know if Flutter hides the initializeDateFormatting from you, but I think if you call this one first it should just short-circuit any later calls to initializeDateFormatting.

```
import 'package:intl/date_symbol_data_local.dart' as basic;
import 'package:intl/src/date_format_internal.dart' as internal;
import 'package:intl/date_symbols.dart';

Future<void> initializeDateFormatting([String? locale, String? ignored]) async {
  internal.initializeDateSymbols(dateTimeSymbolMap);
  internal.initializeDatePatterns(dateTimePatternMap);
}

Map dateTimeSymbolMap() => {... basic.dateTimeSymbolMap(), 
'en_NZ': nzData};

DateSymbols get nzData => basic.dateTimeSymbolMap()['en_US']..FIRSTDAYOFWEEK=4;

Map dateTimePatternMap() => 'similar stuff';
```
