### ISSUE TITLE
Plural options

### ISSUE THREAD

**Issue by FrantisekGazo** [dart-lang/intl#158]
Is somehow possible to spefify different texts for `0`, `1`, `2-4`, `5+` ?

`zero`, `one`, `two` and `other` does not suffice for some languages 😞

**Comment by alan-knight** [comment]
Note that there are also "few" and "many". Which language? This is the convention used by ICU/CLDR, which is widely used for a great many languages.

**Comment by FrantisekGazo** [comment]
Thank you. I tried the `few` and `many` again and it worked. 👍 
You can close this issue.

(I tried it before, but didn't work. The problem was most likely that I was trying it in different language. I thought it will work the same, but looks like it depends on the language.)

FYI: I needed it for Slovak language.

**Comment by M123-dev** [comment]
@FrantisekGazo, how did you managed to get it to work

**Comment by EArminjon** [comment]
@FrantisekGazo  how use few and many ? It didn't work...

**Comment by FrantisekGazo** [comment]
@EArminjon @M123-dev it worked for me when used with Slovak language. Not sure what language you want it for and whether it will work as well.

this is from an old project I worked on when I created this issue: 
(no longer used so I cannot verify whether it's still working or not. the source code is no longer buildable.)
```dart
  String dashboardCompletedRides(count) =>
      Intl.plural(
          count,
          one: 'Najazdili ste 1 jazdu',
          few: 'Najazdili ste $count jazdy',
          many: 'Najazdili ste $count jázd',
          other: 'Najazdili ste $count jázd',
          name: "dashboardCompletedRides",
          args: [count],
          desc: 'compeled rides count',
          examples: const {'count': 1}
      );
```
