### ISSUE TITLE
Question about NumberFormat: '10,00' parsed as '1000.0'

### ISSUE THREAD

**Issue by vnerozin** [dart-lang/intl#160]
var nf = new NumberFormat("#.00");
print(nf.parse('10,00'));
> 1000.0

Why is result 1000.0? I do not have ',' comma in format... 
Is it possible to get error for parsing this number?

**Comment by alan-knight** [comment]
We ignore the grouping separators when parsing, as well as spaces and non-breaking spaces. If you're trying to parse precisely a format you could verify that printing the result is precisely equal to the input string. You could also create a locale with no grouping separator and use that.
