### ISSUE TITLE
Ui text TextDirection implicitly hidden by this plugin TextDirection

### ISSUE THREAD

**Issue by salehahmedZ** [dart-lang/intl#161]
I'm new to flutter, I tried to use this plugin with text that has TextDirection attribute, but it says Ui TextDirection implicitly hidden by this plugin TextDirection.

**Comment by alan-knight** [comment]
I don't know what that means. This package is not Flutter-specific, so that message is probably coming from Flutter, and you should ask there.

**Comment by zoechi** [comment]
Sounds like there are members named `TextDirection` in 2 libraries imported at the same time.

You can use `hide` or `as` with your import
See also https://stackoverflow.com/questions/19723063/what-is-the-difference-between-show-and-as-in-an-import-statement

**Comment by salehahmedZ** [comment]
@zoechi import 'package:intl/intl.dart' as intl; Solved the issue.
Thanks!!

**Comment by alan-knight** [comment]
Oh, duh. Thanks @zoechi
