### ISSUE TITLE
Umbrella Implementations

### ISSUE THREAD

**Issue by Nightsd01** [dart-lang/intl#177]
I am developing a framework for Flutter, and I would like to avoid having a single massive implementation file that contains all class/functions. I would like to split up a lot of this logic into their own implementations to make the project cleaner.

But from what I can see, there is no way to create the Dart equivalent of an 'umbrella header'? 

I'm almost certain there _has_ to be a way to accomplish this, but I cannot find anything through google.

It makes it a bit of a pain to develop potentially large frameworks that offer a lot of functionality to have to lump all of it into a single gigantic `.dart` file. It's also explicitly recommended for users to _not_ "import implementation files from another package"?

**Comment by alan-knight** [comment]
This sounds like a very general question, not something related to Intl.

I suspect that what you want are multiple files within the same package. e.g., see https://www.dartlang.org/guides/libraries/create-library-packages
