### ISSUE TITLE
Documentation of intl refers to a deleted feature (Intl_translation transformer)

### ISSUE THREAD

**Issue by isoos** [dart-lang/intl#179]
_From @roccadev on July 19, 2018 9:23_

URL: https://pub.dartlang.org/packages/intl

**intl_translation 0.17.0** has removed the transformer that allowed to omit the `Intl.message`'s `name` and `args` parameters, but the documentation of intl package still proposes the transformer, or at least it doesn't mention that it's available only in previous version of the library.
PS: I wonder why such a useful feature has been removed...

_Copied from original issue: dart-lang/pub-dartlang-dart#1470_

**Comment by alan-knight** [comment]
Fixed in 0ab279119c354879e7945dc19b81a5ea5078101f
