### ISSUE TITLE
Multiple dart translations in one project

### ISSUE THREAD

**Issue by samiahakmi** [dart-lang/intl#182]
hi,
I have two translations.dart one for each project and another one for the commons translation, I would like to use 2 translations.dart in one project (project_translation.dart and common_translation.dart), is it possible?

**Comment by samiahakmi** [comment]
any suggestion?

**Comment by jaumard** [comment]
Look like it's not supported :( we have your use case and there is no generation/compilation/runtime problem at all, but only the first file is translated correctly, the other(s) one is always in English :( 

```

import 'package:intl/intl.dart';
import 'package:kiwi_mobile/l10n/common_localizations.dart';
import 'package:kiwi_mobile/l10n/error_localizations.dart';
import 'package:kiwi_mobile/l10n/messages/common_messages_all.dart' as common;
import 'package:kiwi_mobile/l10n/messages/error_messages_all.dart' as error;

main() async {
  const localeName = 'es_MX';
  Intl.defaultLocale = localeName;
  await common.initializeMessages('es_MX');
  await error.initializeMessages('es_MX');

  print(CommonLocalizations().finished);
  print(ErrorLocalizations().actionCancelled);

}

```
If the two await are inverted, then error is working but not common... :( 
Is there any workaround for this please ? Because having one translation file is just not good for big projects

**Comment by alan-knight** [comment]
I have done sketch implementations of supporting this in the past, but there are various choices and I haven't settled on anything or had a lot of feedback.

One simple workaround is just to combine the translation data files so there's just one.

If people are interested in playing with something I could publish a branch. The fundamental problem is that we need to provide a context to indicate which messages should be looked up where. The scheme I was thinking of is that each message file can define its own subclass of Intl which looks up in a separate catalog.

**Comment by jaumard** [comment]
I was able to fix by doing this: 

```
import 'dart:async';

import 'package:intl/intl.dart';
import 'package:intl/message_lookup_by_library.dart';
import 'package:intl/src/intl_helpers.dart';

import 'common_messages_en.dart' deferred as common_messages_en;
import 'common_messages_es.dart' deferred as common_messages_es;
import 'error_messages_en.dart' deferred as error_messages_en;
import 'error_messages_es.dart' deferred as error_messages_es;
// ignore: implementation_imports


//FIXME until https://github.com/dart-lang/intl/issues/9 is fixewe need this

// ignore: prefer_generic_function_type_aliases
typedef Future<bool> LibraryLoader();

Map<String, LibraryLoader> _deferredLibraries = {
  'en': () async {
    await common_messages_en.loadLibrary();
    await error_messages_en.loadLibrary();
    return true;
  },
  'es': () async {
    await common_messages_es.loadLibrary();
    await error_messages_es.loadLibrary();
    return true;
  },
};

Map<String, Function> _translations = {
  'en': () {
    return Map.from(common_messages_en.messages.messages)..addAll(error_messages_en.messages.messages);
  },
  'es': () {
    return Map.from(common_messages_es.messages.messages)..addAll(error_messages_es.messages.messages);
  },
};

MessageLookupByLibrary _findExact(localeName) {
  switch (localeName) {
    case 'en':
    case 'es':
      return MessageLookup(localeName);
    default:
      return null;
  }
}

/// User programs should call this before using [localeName] for messages.
Future<bool> initializeMessages(String localeName) async {
  final availableLocale = Intl.verifiedLocale(localeName, (locale) => _deferredLibraries[locale] != null, onFailure: (_) => null);
  if (availableLocale == null) {
    return Future.value(false);
  }
  final lib = _deferredLibraries[availableLocale];
  await (lib == null ? Future.value(false) : lib());
  initializeInternalMessageLookup(() => CompositeMessageLookup());
  messageLookup.addLocale(availableLocale, _findGeneratedMessagesFor);
  return Future.value(true);
}

bool _messagesExistFor(String locale) {
  try {
    return _findExact(locale) != null;
    // ignore: avoid_catches_without_on_clauses
  } catch (e) {
    return false;
  }
}

MessageLookupByLibrary _findGeneratedMessagesFor(locale) {
  final actualLocale = Intl.verifiedLocale(locale, _messagesExistFor, onFailure: (_) => null);
  if (actualLocale == null) {
    return null;
  }
  return _findExact(actualLocale);
}

class MessageLookup extends MessageLookupByLibrary {
  @override
  final String localeName;
  @override
  Map<String, Function> messages;

  MessageLookup(this.localeName) : messages = Map.from(_translations[localeName]());
}

```
Which is better imho that having a custom Intl class. 

@alan-knight I don't mind if Intl have internally only one dictionary with all translations, but I want to be able to have multiple file on my side.(basically that's what my fix here do). I think one way to support multiple dart translation is to simply generate automatically the code I shared here when we detect multiple files.

**Comment by alan-knight** [comment]
Thanks. That's very useful feedback. Note that when I say there'd be a separate Intl subclass, it would be a tiny one that's generated along with the data, so it wouldn't require separate effort on your part. But it doesn't sound like you need what that would provide anyway.

So if I understand correctly, you just want to have multiple translation files. You're OK if they're all loaded at the same time.

That seems like it would work for you if it just allowed more than one input translation file per locale
``
    dart .../generate_from_arb.dart one.dart two.dart etc.dart common_fr.arb errors_fr.arb common_es.arb errors_es.arb ...
``

which would be quite a small modification. Is that correct?

**Comment by jaumard** [comment]
In my code they are loaded at the same time per language, not all language. I'm perfectly ok with this :)  
I suppose providing more than one file will totally do the job for my use case then instead of `common_messages.fr.dart` and `error_messages.fr.dart` I'll have just one FR file right ? Look like a small modification indeed that could unlock multiple files :)

**Comment by alan-knight** [comment]
Can you try the multipleArb branch and see if that does what you want?

**Comment by jaumard** [comment]
Sure @alan-knight I'll give it a try asap

**Comment by jaumard** [comment]
Just tested @alan-knight, look like it work like a charm ! :)

**Comment by alan-knight** [comment]
A full implementation is now pushed to master. It isn't in a release yet, but you can run it from HEAD.
