### ISSUE TITLE
(misuse of) Intl.select with translations enabled throws exception instead of using the 'other' value

### ISSUE THREAD

**Issue by arcra** [dart-lang/intl#187]
Code triggering this behavior:

```
String myMessage(MyClass source) {
  String sourceStr = source.toString();
  return Intl.select(
      sourceStr,
      {
        'UNKNOWN': 'Default message',
        'VALUE_1': 'Value 1',
        'VALUE_2': 'Value 2',
        'other': 'unsupported',
      },
      args: [source],
      name: 'myMessage',
      desc: 'My cool message',
      examples: const {'sourceStr': 'VALUE_1'});
}
```
The translation generation tool seems to be using the parameter in the wrapping function to determine which option in the map it should be using, and one being a custom class, and the options being strings, apparently it's not finding a valid option and fails.

The generated file for translated messages has this entry: (Note the index: -1)

```
"myMessage": [
  "Intl.select",
  -1,
  {
    "UNKNOWN": "Default message in french",
    "VALUE_1": "Value 1 in french",
    "VALUE_2": "Value 2 in french",
    "other": "unsupported in french"
  }
],
```

While I understand this use case might not be supported. We were expecting this should result in the 'other' value being used.
The actual behavior throws an exception ("Index out of range: index must not be negative: -1") and made our Angular app completely break (components were not rendered properly and the page was unresponsive)

**Comment by mosuem** [comment]
I assume this is rather due to the line `args: [source]` instead of `args: [sourceStr]`?
