### ISSUE TITLE
I'm using version 2.1 of dart and it will not work in this version

### ISSUE THREAD

**Issue by pinkpigsong** [dart-lang/intl#190]
The current Dart SDK version is 2.1.0-dev.7.1.flutter-b99bcfd309.

Because flutter_app depends on intl_translation >=0.14.0+1 <0.17.0 which requires SDK version >=1.12.0 <2.0.0, version solving failed.

**Comment by zoechi** [comment]
Can you please post the dependencies and dev_dependencies in your `pubspec.yaml`?

**Comment by pinkpigsong** [comment]
> 당신은 당신의 의존성과 dev_dependencies를 게시 할 수 있습니까 `pubspec.yaml`?


Sorry, I was using version 0.15.
The problem was that the description of the[ intl package](https://pub.dartlang.org/packages/intl) was used as is.
