### ISSUE TITLE
error on format due to timezone

### ISSUE THREAD

**Issue by lejard-h** [dart-lang/intl#196]
if you take the following code
```dart
  final format = DateFormat('dd/MM/y');

  final str = '05/08/2018';
  final date = format.parseLoose(str);

  print(date);
  print(format.format(date));
```

it print `2018-08-05 00:00:00.000` and `05/08/2018` with `Europe/Paris` timezone

but with `America/Denver`

```
FormatException: Error parsing 05/08/2018, invalid hour value: 0. Expected value between 15 and 15. Date parsed as 2018-08-04 15:00:00.000. at package:intl/src/intl/date_format_helpers.dart 130:7
```

related PR on angular_components https://github.com/dart-lang/angular_components/pull/360

**Comment by alan-knight** [comment]
This doesn't reproduce for me on a Mac setting the timezone to Denver via the GUI. Do you have any more details?

**Comment by lejard-h** [comment]
Yes sorry, I tested on browser and changed timezone using Timeshift extension for chrome
https://chrome.google.com/webstore/detail/change-timezone-time-shif/nbofeaabhknfdcpoddmfckpokmncimpj

**Comment by alan-knight** [comment]
I tried it on Linux setting the TZ environment variable before launching Chrome. It changes the result of DateTime.now() appropriately, so it seems to be working, and I had no problem running the code in DDC or in dart2js.  I'm not keen to run an extension with that kind of blanket permission on my Google account, but maybe it's related to the extension?
