### ISSUE TITLE
public API should use Object, not dynamic, when not calling any methods

### ISSUE THREAD

**Issue by srawlins** [dart-lang/intl#197]
For example, [Intl.message](https://github.com/dart-lang/intl/blob/master/lib/intl.dart#L180) takes a `List args` parameter, which should be a `List<Object>`.

For parameters like this, where no methods are actually called on the argument, Object is a better choice than dynamic. It protects against assuming a type in the future, and calling methods on that assumed type. It also prevents "implicit-dynamic" errors when literals are passed in.

As another example, Intl.message takes in a `Map<String, dynamic> examples`. `--no-implicit-dynamic` reports when a literal Map, e.g. `{"foo": "bar"}` is passed in, asking the user to spell out types like `<String, String>{"foo": "bar"}`. It makes more sense to just declare the values an Object rather than dynamic.

Effective Dart [covers](https://www.dartlang.org/guides/language/effective-dart/design#do-annotate-with-object-instead-of-dynamic-to-indicate-any-object-is-allowed) this recommendation as well.

**Comment by srawlins** [comment]
CC @alan-knight @matanlurey

**Comment by matanlurey** [comment]
This seems like a no brainer, non-breaking change.
