### ISSUE TITLE
NumberFormat documentation is referring to non-existent decimalFormat, percentFormat, etc

### ISSUE THREAD

**Issue by apaatsio** [dart-lang/intl#202]
The documentation mentions `decimalFormat`, `percentFormat`, `scientificFormat`, and `currencyFormat`, none of which exist. I suppose these should be `decimalPattern`, `percentPattern`, `scientificPattern`, and `currency`, respectively.

https://github.com/dart-lang/intl/blob/5e0817412a746f5329d18ff3eba9c2b46104f935/lib/src/intl/number_format.dart#L36-L45

**Comment by alan-knight** [comment]
Thanks. There are also several more constructors than when that was written. Update pending.
