### ISSUE TITLE
Get day/month/year order for the local

### ISSUE THREAD

**Issue by xster** [dart-lang/intl#205]
The documentation is clear on how to get the datetime formatted given a pattern. But it's not clear on how to ask it the question of what is the most standard order pattern for the local in arranging day, month, year in a date.

**Comment by alan-knight** [comment]
I don't think we can support this. You could do it by getting the pattern and examining it. Or you could just give it known values and look at the output to infer that. But it's complicated, and going forward we'd like to be able to delegate to things like JS Intl that aren't going to give us that information.
