### ISSUE TITLE
Dateformat not parsing after a format generated string

### ISSUE THREAD

**Issue by rmarau** [dart-lang/intl#210]
Given this `"yyyyMMddHHmmss"` format:
`DateFormat("yyyyMMddHHmmss").format(DateTime.now());` gives a nice string like: `"20190405140723"` as I would expect.

Now reversely parsing...
`DateFormat("yyyyMMddHHmmss").parse("20190405140723");` throws the message "Trying to read MM from 20190405140723 at position 14"

It seems the parser consumes the whole string (after the 2019) while searching for some separator that I don't have in the format.

Shouldn't parse and format be reversible?

I've tried with parseLoose and parseStrict: same result.
Using intl version: "0.15.8"

**Comment by rmarau** [comment]
Workaround: Injecting a separator.

`DateFormat("yyyy MM dd HH mm ss").parse("2019 04 05 14 07 23")`

**Comment by alan-knight** [comment]
You probably don't really want to do this. I'm going to guess that you are not really planning to present these strings to users and have them type them in, but more likely you're consuming them from some other system. In which case this is both a very slow way of parsing a string of known fixed length integer fields and one which will behave differently in different locales. Also, in the longer term it would be good to delegate this functionality to e.g. JS Intl, where available, and it doesn't provide direct access to patterns.

**Comment by rmarau** [comment]
Got it. Thanks

I understand this is an intl package not a data parsing package. I was using it for the convenience on handling DateTime directly. Performance is not really an issue in my case.

Still:
 - I find it odd the two methods `format` and `parse` won't work reversibly for the same DateFormat. I was misled by the Java's SimpleDateFormat that works fine on this.
 - In this specific pattern "yyyyMMddHHmmss" I dont think the result would (for now)  vary with locales. It's all numbers and the oackage is not outputting other symbols than 0-9. Forcing a locale would make it safe to use.

Thanks for the prompt response

**Comment by alan-knight** [comment]
I'm not sure what would be involved in being fully reversible, but generally it's trying to optimize more for human input than reversibility. So e.g. MM will happily accept '4', and not require '04'.

For varying, try  DateFormat('yyyyMMddHHmmss', 'ar_EG').format(DateTime.now())

If you force a Locale it doesn't vary, but then it's just a slow way to parse a fixed format.

**Comment by rmarau** [comment]
You're totally right!
Before replying, I did my self a test using "zh_CN" and got decimal numbers. I should have looked deeper.
Thanks anyway.

**Comment by natebosch** [comment]
Reopening to use this issue to centralize discussion.

I do think that if we don't support these patterns we should make it more obvious. We should add a note to the docs. I think we should also try to add a specific error for attempting to parse with a format string that has no delimiters. Ideally we'd be able to mention that intl is intended for human formats, and that machine formats should use a different approach. I can't think of any Dart team supported libraries for this.

**Comment by mosuem** [comment]
This is now implemented as a class `FixedDateTimeFormatter` in [package:convert](github.com/dart-lang/convert).

**Comment by eximius313** [comment]
@mosuem I think there is a problem with `FixedDateTimeFormatter`

this code:
```dart
    String s1 = '2022 10 21 14 59 08';
    String s2 = '20221021145908';
    DateTime d1 = DateFormat('yyyy MM dd HH mm ss').parse(s1);
    print("D1 $d1");
    DateTime d2 = FixedDateTimeFormatter('yyyyMMddHHmmss').decode(s2);
    print(d2);
    DateTime d3 = FixedDateTimeFormatter('YYYYMMDDhhmmss').decode(s2);
    print(d3);
```

produces:
```
D1: 2022-10-21 14:59:08.000
D2: 0000-10-01 00:59:08.000Z
D3: 2022-10-21 14:59:08.000Z
```

Clearly `yyyyMMddHHmmss` does't work as expected

**Comment by mosuem** [comment]
In the documentation for `FixedDateTimeFormatter`, it states 
```
/// The allowed characters are
/// * `Y`	for “calendar year”
/// * `M`	for “calendar month”
/// * `D`	for “calendar day”
/// * `E`	for “decade”
/// * `C`	for “century”
/// * `h`	for “clock hour”
/// * `m`	for “clock minute”
/// * `s`	for “clock second”
/// * `S`	for “fractional clock second”
```
so `YYYYMMDDhhmmss` would indeed be the correct format string, which seems to work exactly as expected. The missing `Z` in the first string can be attributed to the `utc = false` in the `DateFormat.parse` method.

```
String s1 = '2022 10 21 14 59 08';
DateTime d1 = DateFormat('yyyy MM dd HH mm ss').parse(s1, true);
print("D1: $d1");
String s2 = '20221021145908';
DateTime d3 = FixedDateTimeFormatter('YYYYMMDDhhmmss').decode(s2);
print("D3: $d3");
```
Works as expected.

**Comment by eximius313** [comment]
While documentation of `DateFormat` states:
```
/// The following characters are available in explicit patterns:
///
///     Symbol   Meaning                Presentation       Example
///     ------   -------                ------------       -------
///     G        era designator         (Text)             AD
///     y        year                   (Number)           1996
///     M        month in year          (Text & Number)    July & 07
///     L        standalone month       (Text & Number)    July & 07
///     d        day in month           (Number)           10
///     c        standalone day         (Number)           10
///     h        hour in am/pm (1~12)   (Number)           12
///     H        hour in day (0~23)     (Number)           0
///     m        minute in hour         (Number)           30
///     s        second in minute       (Number)           55
///     S        fractional second      (Number)           978
///     E        day of week            (Text)             Tuesday
///     D        day in year            (Number)           189
///     a        am/pm marker           (Text)             PM
///     k        hour in day (1~24)     (Number)           24
///     K        hour in am/pm (0~11)   (Number)           0
///     Q        quarter                (Text)             Q3
```
don't we want to be consistent?

**Comment by mosuem** [comment]
The problem is that there are multiple standards we could be consistent with, see also the [comment in the review](https://github.com/dart-lang/convert/pull/66#discussion_r981086996). If you disagree, please open an issue in the convert repository, where this code lives.

**Comment by eximius313** [comment]
@mosuem 
as you requested: https://github.com/dart-lang/convert/issues/70
