### ISSUE TITLE
iw_IL dateformat missing

### ISSUE THREAD

**Issue by ened** [dart-lang/intl#214]
When trying to instantiate a DateFormat class for the hebrew locale (iw_IL), the following error is thrown:

```
Invalid argument(s): Invalid locale 'iw_IL'
When the exception was thrown, this was the stack:
#0      Intl._throwLocaleError (package:intl/intl.dart:239:5)
#1      Intl.verifiedLocale (package:intl/intl.dart:233:21)
#2      new DateFormat (package:intl/src/intl/date_format.dart:246:20)
#3      new DateFormat.yMMMMEEEEd (package:intl/src/intl/date_format.dart:436:37)
```

For the moment we will fallback to `en_US`, but is it possible to support this locale in the future?

Thank you, 
Sebastian

**Comment by alan-knight** [comment]
There is 'iw' locale data (https://github.com/dart-lang/intl/blob/eb4ab704c4a3c48d957b2a188c6b452051a093a7/lib/date_symbol_data_local.dart#L9083 ) and I would expect iw_IL to fall back to that.

**Comment by ened** [comment]
Does the error message point to another issue in this case? I will retest..

**Comment by alan-knight** [comment]
It doesn't suggest anything obvious. But the following works for me.

```
import 'package:intl/intl.dart';
import 'package:intl/date_symbol_data_local.dart';
...
  await initializeDateFormatting('iw_IL');
  Intl.systemLocale = 'iw_IL';
  var d = DateFormat.yMMMMEEEEd();
  print(d.format(DateTime.now()));
```

and produces 

```
יום שישי, 14 ביוני 2019
```
