### ISSUE TITLE
Context key?

### ISSUE THREAD

**Issue by alexei-g-aloteq** [dart-lang/intl#216]
Thank you for hard work on this module - it looks so solid...

Unfortunately, I can not find one very useful feature - a context key.
This is simple idea to add any additional string that represents the sentence context.
Usually a context is a screen name, where the sentence is used.

I'm using it for cases when different screens should have different translations for the same sentence. So far, I see that this library has no such option - given sentence can have only single translation for every locale.

Did I missed it?

**Comment by alan-knight** [comment]
That sounds like the "meaning" parameter.

**Comment by alexei-g-aloteq** [comment]
Partially, but the meaning parameter is descriptive only. It can not be used to create another variant of translation for the same original.

**Comment by alan-knight** [comment]
Description is descriptive only. Meaning is used in computing the lookup.
At least it is in Google's internal system, so unless there's a difference
I'm not aware of with the ARB support it should work.

**Comment by alexei-g-aloteq** [comment]
Can you please suggest how to act if I need the same text to be translated differently based on the screen?

**Comment by alan-knight** [comment]
Sure, do something like
https://github.com/dart-lang/intl_translation/blob/master/test/message_extraction/sample_with_messages.dart#L151
https://github.com/dart-lang/intl_translation/blob/master/test/message_extraction/sample_with_messages.dart#L156

and you should get results like
https://github.com/dart-lang/intl_translation/blob/master/test/message_extraction/verify_messages.dart#L143
