### ISSUE TITLE
NumberFormat.compact() - No notation for thousands in German

### ISSUE THREAD

**Issue by lukasschneiderapps** [dart-lang/intl#218]
The compact number format for German does not have a notation for thousands.

When formatting 100000 with NumberFormat.compact() in German I get:

100000

The desired result would be:

100 Tsd.

(In English it works: 100 K)

Code example:
`NumberFormat.compact(locale: "de").format(100000);`

**Comment by alan-knight** [comment]
We are likely to change compact number formatting to delegate to native facilities (JS Intl, ICU, ...)

**Comment by mosuem** [comment]
`Tsd` does not occur in the [CLDR data](https://st.unicode.org/cldr-apps/v#/de/Compact_Decimal_Formatting/ff7ca46dee120b1), which is the source of truth for this repository. This is thus expected behavior.
