### ISSUE TITLE
Invalid locale 'mg' (Madagascar)

### ISSUE THREAD

**Issue by bradyt** [dart-lang/intl#222]
Why does Madagascar not work with this library? Whereas `'en'` works fine.

``` dart
import 'package:intl/intl.dart';

main() => print(NumberFormat(null, 'mg'));
```

```
Unhandled exception:
Invalid argument(s): Invalid locale 'mg'
#0      Intl._throwLocaleError (package:intl/intl.dart:239:5)
#1      Intl.verifiedLocale (package:intl/intl.dart:233:21)
#2      new NumberFormat._forPattern (package:intl/src/intl/number_format.dart:496:24)
#3      new NumberFormat (package:intl/src/intl/number_format.dart:173:11)
#4      main (file:///Users/alice/code/dartpad/bin/dartpad.dart:37:9)
<asynchronous suspension>
#5      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#6      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

Links:

- https://en.wikipedia.org/wiki/Madagascar
- https://en.wikipedia.org/wiki/ISO_3166
- https://en.wikipedia.org/wiki/ISO_3166-2:MG

**Comment by cskau-g** [comment]
The data used in `intl` is derived from CLDR (35) as mentioned in [number_symbols_data.dart](https://github.com/dart-lang/intl/blob/master/lib/number_symbols_data.dart).

[CLDR 35](https://github.com/unicode-org/cldr/tree/release-35-1/common/main) does have `mg`, but we have a whitelist in the generator tool which does not include `mg`.

Alan, is there a good reason we're not just generating data for all the locales? The whitelist is inherited from a different project and Dart even has a small additional whitelist on top of that, so I suspect we can just do away with the whitelist all together.

**Comment by alan-knight** [comment]
The whitelist is copied from Closure, and from a few years ago, so it is probably out of date. The main concern in removing the whitelist outright is data size. There are potentially a lot of locales, many of which are very minor variations. Adding something to the whitelist is relatively easy. Note that you can also add a locale programmatically as a workaround. See https://github.com/dart-lang/intl/blob/master/test/date_time_format_custom_test.dart
