### ISSUE TITLE
Ordinal day 1th 2nd,etc

### ISSUE THREAD

**Issue by amreniouinnovent** [dart-lang/intl#226]
I wonder if you could support ordinal number for the day of the month
1st, 2nd,3rd,4th, 21st, etc

I used a function but I think `DateFormat `should support it

```
  String today() {
    final DateTime now = DateTime.now();
    String suffix = 'th';
    final int digit = now.day % 10;
    if ((digit > 0 && digit < 4) && (now.day < 11 || now.day > 13)) {
      suffix = <String>['st', 'nd', 'rd'][digit - 1];
    }
    return DateFormat("E, MMM d'$suffix'").format(now); // 'Sun, Jun 30th'
  }
```

**Comment by alan-knight** [comment]
We probably won't do this directly in Dart, as the current formatting is implemented. The underlying facilities in browsers are better now, so we're likely to add things by making them pass through to JS Intl in browsers, and to ICU or operating system libraries on other platforms.

**Comment by amreniouinnovent** [comment]
@alan-knight As you mentioned it won't be implemented directly in intl I opened an issue in the FLutter repo
https://github.com/flutter/flutter/issues/37221
I will close this issue for now..if you improve the proposal on the flutter repo please put your ideas there.
Thank you.

**Comment by suztomo** [comment]
I have the same need for this for showing birthdays. Given a number, I want to show "st", "nd", "rd", or "th". For example,
"1st birthday", "2nd birthday", "3rd birthday" ... "11th birthday", ... "21st birthday", ... "101st birthday".

**Comment by AlexanderFarkas** [comment]
It seems reasonable to implement it in dart. Web does ordinals better, but what about mobile - is calling native Kotlin/Swift option?
Also, ordinals are not magic, it's pure calculus.
