### ISSUE TITLE
 Time zone format throws an UnimplementedError

### ISSUE THREAD

**Issue by mdryankov** [dart-lang/intl#229]
This is something that is supposed to work according to the documentation:

https://api.flutter.dev/flutter/intl/DateFormat-class.html

Reference: https://github.com/dart-lang/intl/blob/5be03cb1d6613f546702d7ea51bf41e4443d04ca/lib/src/intl/date_format_field.dart#L626

https://github.com/dart-lang/intl/blob/5be03cb1d6613f546702d7ea51bf41e4443d04ca/lib/src/intl/date_format_field.dart#L631

https://github.com/dart-lang/intl/blob/5be03cb1d6613f546702d7ea51bf41e4443d04ca/lib/src/intl/date_format_field.dart#L635

**Comment by ilyaivanov** [comment]
From the [docs](https://pub.dev/packages/intl) 

> Known limitations: Time zones are not yet supported. Dart DateTime objects don't have a time zone, so are either local or UTC. Formatting and parsing Durations is not yet implemented.

:(

**Comment by jamesderlin** [comment]
This seems like a duplicate of https://github.com/dart-lang/intl/issues/19 or https://github.com/dart-lang/intl/issues/74.

**Comment by mosuem** [comment]
Yes, unfortunately it is... Closing in favor of #19 .
