### ISSUE TITLE
Error import with Flutter Web

### ISSUE THREAD

**Issue by vico-aguado** [dart-lang/intl#232]
Hi!

I need to use DateFormat in Flutter web (1.10.5 SDK) but I get this error in my terminal:

Unable to find modules for some sources, this is usually the result of either a
bad import, a missing dependency in a package (or possibly a dev_dependency
needs to move to a real dependency), or a build failure (if importing a
generated file).

Please check the following imports:

`import 'package:intl/intl.dart';` from template|lib/src/app/browser/pages/tickets_page.dart at 7:1

Could you help me?

Thanks!

**Comment by alan-knight** [comment]
Are you missing an entry for intl in your pubspec? That seems pretty straightforward, and I don't see anything else much to go wrong.
