### ISSUE TITLE
Wish for an explicit description of the 0.16.0 breaking change

### ISSUE THREAD

**Issue by amirh** [dart-lang/intl#233]
Hi,
It's not completely clear from the changelog what was the breaking change in 0.16.0.
An explicit description of the breaking change would help.

Context: we're trying to figure out if we need a major version bump when upgrading the local_auth plugin to this version (https://github.com/flutter/plugins/pull/2084).

**Comment by alan-knight** [comment]
I don't think that there's anything that is backward-compatibility breaking. There were some significant additions, notably the Locale class, although it's not very exposed yet, and it increases the supported analyzer version, but there are no API changes. Sorry for the confusion.
