### ISSUE TITLE
Add Intl.allMessages() to intl library

### ISSUE THREAD

**Issue by pedrospj** [dart-lang/intl#234]
I can't find a way of loading all messages from a .arb file.

Instead of doing
`Intl.message(<message_name>)` for all messages in the file, it would be nicer just doing:
`final <Map<String, String> messages = Intl.allMessages()`
and then get the messages by doing:
`messages[<message_name>]`.

**Comment by alan-knight** [comment]
Messages that have parameters wouldn't be strings. And in general the actual representation of the messages internally isn't strings and varies depending on the command-line options from intl_translations.
