### ISSUE TITLE
Update MessageIfAbsent signature to be compatible with intl_translation

### ISSUE THREAD

**Issue by daniel-v** [dart-lang/intl#235]
There is an incompatibility between this package and `intl_translation`. The generated signature of `MessageIfAbsent` collides with the generated version of it.

I've opened an issue in the other project as well, not sure where you guys would want to fix it. Please see: https://github.com/dart-lang/intl_translation/issues/78

In short: code generation expects https://github.com/dart-lang/intl/blob/0.16.0/lib/src/intl_helpers.dart#L14 to have a `String` return type.

**Comment by alan-knight** [comment]
This seems to be fixed on master.
