### ISSUE TITLE
Can't pub upgrade because of error in the latest version pubspec file. (Unexpected character)

### ISSUE THREAD

**Issue by YoussefLasheen** [dart-lang/intl#236]
I get this error when I try to run `flutter upgrade`.
Version 0.16.0

`Error on line 1, column 1 of ..\..\.pub-cache\hosted\pub.dartlang.org\intl-0.16.0\pubspec.yaml: Unexpected character.
  ╷
1 │
  │ ^
  ╵
Error (65): Unable to 'pub upgrade' flutter tool. Retrying in five seconds...`

I tried  `pub cache repair` but it doesn't help. 
The only way to solve this problem is to delete .\flutter\.pub-cache\hosted\pub.dartlang.org\intl-0.16.0

**Comment by alan-knight** [comment]
That doesn't seem to be a general problem, it sounds like you may have cache corruption? If you're still seeing the problem after deleting the pub cache please re-open.
