### ISSUE TITLE
Incorrect decimal separator in NumberFormat on iOS with region settings

### ISSUE THREAD

**Issue by Szfymen** [dart-lang/intl#238]
Hello, I have faced issue related to language and region settings on iOS. I will give you an example based on my settings.

On iOS when you set system language to Polish and region settings to Poland (pl_PL) system will provide number formatting with "," decimal separator.

On the other hand, if you set language to English and region to United Kindom (en_GB) it will provide "." decimal separator.

For both above examples, NumberFormat works as expected.

The problem starts if when you set language to English and region to Poland (en_PL) - the iOS system will format values same as in Poland region settings (so "," decimal separator) but NumberFormat uses English formatting (with "."). That leads us to issue because system keyboard shows comma, which is treated by NumberFormat as group separator - so there is no possibility to type in decimal number. 

Currently what I have done to avoid this issue is add numerFormatSymbol for (en_PL), which is same as (pl). 
But I'm afraid that many other edge cases are facing same issue.

Is currently anyway to avoid this issue, maybe I'm doing something wrong?

**Comment by alan-knight** [comment]
Unfortunately that's probably the best solution at the moment. The fallback logic is very simple and not customizable. So if it doesn't find en_PL it will fall back to en. I'm not sure how you're adding en_PL, but you can do it programmatically by adding a locale to the map, based off one that's already in there. I've seen this used, for example, to customize particular Arabic locales to use native or latin digits.
