### ISSUE TITLE
Currency formatter with negative numbers should use non-breaking hyphen

### ISSUE THREAD

**Issue by evelyne24** [dart-lang/intl#242]
I am using `NumberFormat` to format currency. The formatter is initialised as such:

 `final NumberFormat currencyFormatter = NumberFormat.simpleCurrency(locale: 'en_GB', name: 'GBP', decimalDigits: 2);`

Negative numbers are formatted with normal hyphens `-`, but I think instead should be formatted with [non-breaking hyphens](https://www.toptal.com/designers/htmlarrows/punctuation/non-breaking-hyphen/). 

For example, using the formatted string `-£10,000.00` in Flutter in a `Text` widget results in the widget wrapping the text after the hyphen, which is incorrect. Manually replacing it with a non-breaking hyphen solves the problem.

So inside `NumberFormat.dart`, line 50, instead of 

```
class NumberFormat {
  /// Variables to determine how number printing behaves.
  // TODO(alanknight): If these remain as variables and are set based on the
  // pattern, can we make them final?
  String _negativePrefix = '-';
```

I believe it should use the Unicode character for non-breaking hyphen, `\u2011`.

**Comment by alan-knight** [comment]
We get those values from CLDR, so we can't really change them. So it isn't so much the variable you reference there as the locale data, e.g. https://github.com/dart-lang/intl/blob/master/lib/number_symbols_data.dart#L33

If ICU or someone else authoritative formats with the non-breaking hyphen that would be a reason to re-examine, but I don't think we want to diverge from those.
