### ISSUE TITLE
incompatible

### ISSUE THREAD

**Issue by guikebr** [dart-lang/intl#245]
Because every version of pattern_formatter depends on intl ^0.15.7 and every version of flutter_localizations from sdk depends on intl 0.16.0, pattern_formatter is incompatible with flutter_localizations from sdk.
So, because localize depends on both flutter_localizations any from sdk and pattern_formatter ^0.0.3, version solving failed.
pub get failed (1; So, because localize depends on both flutter_localizations any from sdk and pattern_formatter ^0.0.3, version solving failed.)

**Comment by alan-knight** [comment]
That sounds like an issue for pattern_formatter, that it needs to upgrade. If Flutter pins the version of Intl, I don't think there's anything we can do about other packages that depend on a different version.
