### ISSUE TITLE
DateFormat.E and DateFormat.EEE returning the same

### ISSUE THREAD

**Issue by edeuss** [dart-lang/intl#249]
Spent a few hours today trying to figure out what happened to my project and apparently `DateFormat.E` and `DateFormat.EEE` Are returning the same thing even though they should not be.

`DateFormat.E` should return the abbreviated version of the weekday. (Example: `Mon`)
`DateFormat.EEE` should return the weekday. (Example: `Monday`)

**Comment by jamesderlin** [comment]
> `DateFormat.EEE` should return the weekday. (Example: `Monday`)

According to what?  The [`DateFormat` documentation](https://pub.dev/documentation/intl/latest/intl/DateFormat-class.html) says that you need to use `EEEE` for a full weekday name.
