### ISSUE TITLE
Issue with device locale

### ISSUE THREAD

**Issue by CripyIce** [dart-lang/intl#255]
Hi there,
I'm having issues with changing locale for `Intl` using `Intl.defaultLocale` or `findSystemLocale()`.
It appears when using `Intl.defaultLocale` and setting locale to `fr`/`fr_FR` or `findSystemLocale()` on a real device with french locale, date formatting is not working.
I've tried setting different locales but none of them seems to be working except for English locale.
I would appreciate the help, or even a code example.

This is the code i'm using for example - different locale method from the example above, but still should work:
```dart
final format = DateFormat("yyyy-MM-dd").parse("2020-01-15");
return DateFormat.yMMMMd("fr").format(format);
```

Thanks!

**Comment by alan-knight** [comment]
Have you called initializeDateFormatting()?
