### ISSUE TITLE
Incorrect am/pm marker between 12 to 1 pm

### ISSUE THREAD

**Issue by apgapg** [dart-lang/intl#257]
The am/pm marker is wrong when we try to parse an iso date string between 12 to 1 pm.
See the code below and it's output. 
12 hrs becomes 00 hrs. This causes 12:23 am to show instead of 12:23 pm for eg
This only happens between 12 to 1 pm. Though i didn't check it in midnight between 00:00 to 12:59 am
```
 @override
  void initState() {
    // TODO: implement initState
    super.initState();
    final time = DateTime.now().toIso8601String();
    print(DateTime.now().toIso8601String());
    print(DateFormat("yyyy-MM-ddThh:mmZ").parse(time));
  }
```

Using version   intl: ^0.16.0
Locale India

<img width="1552" alt="Screenshot 2020-02-13 at 12 38 13 PM" src="https://user-images.githubusercontent.com/13887407/74409929-df176980-4e5d-11ea-8f96-2093d77d5529.png">

**Comment by apgapg** [comment]
Jiffy package works fine. It hows pm.

**Comment by avirias** [comment]
> Jiffy package works fine. It hows pm.

Thanks man

**Comment by Brady-F** [comment]
I also have this issue.

**Comment by mosuem** [comment]
You are using the character `h` for hours, which is specified as `hour in am/pm (1~12)`. Using `H`, described as `hour in day (0~23) `, is probably what you would want here, as this character is also used in the [toIso8601String](https://api.flutter.dev/flutter/dart-core/DateTime/toIso8601String.html) method.
This gives the desired result:
```
import 'package:intl/date_symbol_data_local.dart';
import 'package:intl/intl.dart';

Future<void> main(List<String> arguments) async {
  await initializeDateFormatting("in");
  var dateTime = DateTime(2022, 10, 19, 12, 30).toIso8601String();
  print(dateTime); // prints 2022-10-19T12:30:00.000
  print(DateFormat("yyyy-MM-ddTHH:mmZ").parse(dateTime)); // prints 2022-10-19 12:30:00.000
}
```


Please reopen this if it does not solve your question.
