### ISSUE TITLE
Is any way to parse a date string base on this year

### ISSUE THREAD

**Issue by jimmyshiau** [dart-lang/intl#260]
Default `_DateBuilder` base on 1970, is any way to change year of _DateBuilder?
```
final fmt = new DateFormat.MMMd();
  print(fmt.parse('Feb 29'));//1970-03-01 00:00:00.000
  print(fmt.parseStrict('Feb 29'));
// dart_sdk.js:5145 Uncaught Error: FormatException: Error parsing Feb 29, 
//invalid day value: 29. Expected value between 1 and 1. 
//Date parsed as 1970-03-01 00:00:00.000
```

**Comment by mosuem** [comment]
I don't think there is a good solution to this - specifying month and day just isn't enough to specify a `DateTime`, as shown by your example. If you expect a date of the form `MMMd`, I would append a leap year, for example `DateFormat('MMM d yyyy').parse('Feb 29 2016')`. Take care of choosing a leap year, which can be determined through an [algorithm](https://en.wikipedia.org/wiki/Leap_year#Algorithm).

The `DateFormat` in this package is for locale-specific dates; for simple fixed date parsing and formatting, consider using `package:convert` instead.
