### ISSUE TITLE
Number Format

### ISSUE THREAD

**Issue by winbrignoli** [dart-lang/intl#261]
final formatter = new NumberFormat("#,###.##","en-us");
    print(formatter.format(100.5)); 

produces this output:
flutter: 100.5
expected output is:
100.50

**Comment by ManuLpz4** [comment]
,##0.00 😄

**Comment by mosuem** [comment]
```
/// The format is specified as a pattern using a subset of the ICU formatting
/// patterns.
///
/// - `0` A single digit
/// - `#` A single digit, omitted if the value is zero
```
But the above comment already has the solution.
