### ISSUE TITLE
Wrong documentation related to timezones

### ISSUE THREAD

**Issue by ristiisa** [dart-lang/intl#264]
The documentation on https://pub.dev/documentation/intl/latest/intl/DateFormat-class.html states that
"The following characters are available in explicit patterns:"
```
...
z        time zone              (Text)             Pacific Standard Time
Z        time zone (RFC 822)    (Number)           -0800
v        time zone (generic)    (Text)             Pacific Time
...
```

But this is false as the functions are not implemented (#74) and these features are NOT available to use.

**Comment by jamesderlin** [comment]
This is now fixed on `master` by fdfc6bf5887b3163ca6f0687a765ed13bf0c7b13.
