### ISSUE TITLE
DateFormat: Formatting Weekdays with unknown Locale does not fallback to English

### ISSUE THREAD

**Issue by lukasschneiderapps** [dart-lang/intl#266]
I'm currently using `DateFormat` to create a localized weekday string.
However when I provide an unknown `Locale` to the DateFormat, the DateFormat does not fallback to English, but to some other Asian language.

Expected Result:

![Screenshot_1583322461](https://user-images.githubusercontent.com/48716544/75876702-77c65700-5e16-11ea-8391-cc21afcb6237.png)

Actual Result:

![Screenshot_1583322505](https://user-images.githubusercontent.com/48716544/75876712-7d23a180-5e16-11ea-98db-e6e6b92161a2.png)

Code:

```
import 'package:flutter/material.dart';
import 'package:intl/intl.dart';
import 'package:intl/date_symbol_data_local.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    initializeDateFormatting('en', null);
    return MaterialApp(
      home: Scaffold(body: MyHomePage()),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Container(
      child: Center(
        child: Text(DateFormat("EEEE", Locale("test", "test").languageCode)
            .format(DateTime.fromMicrosecondsSinceEpoch(12341234))),
      ),
    );
  }
}
```

**Comment by mosuem** [comment]
This is because currently, if the locale is not found in the list of locales, it tries to take the `shortLocale` of the given string. This is just the first two letters, which is `te` for `test`, short for [Telugu](https://en.wikipedia.org/wiki/Telugu_language).
