### ISSUE TITLE
eras vs eranames for locale "ru"

### ISSUE THREAD

**Issue by aam** [dart-lang/intl#270]
ERAS and ERANAMES for Russian locale are inconsistent.

Seems strange to have ERAS and ERANAMES being different for "ru" locale:
https://github.com/dart-lang/intl/blob/master/lib/date_symbol_data_local.dart#L13966
```
      "ru": new DateSymbols(
          NAME: "ru",
          ERAS: const ['до н. э.', 'н. э.'],
          ERANAMES: const ['до Рождества Христова', 'от Рождества Христова'],
```

"до н.э." is short for "до нашей эры" ("before our era"), "н.э." - for "нашей эры"("of our era").
ERANAMES on the other hand are "до Рождества Христова"("before the birth of Christ"), "от Рождества Христова"("after the birth of Christ").

Either ERAS should be changed to `const ['до Р.Х.', 'от Р.Х.']` or ERANAMES should be changed to `const ['до нашей эры', 'нашей эры']`.

I believe latter is used more frequently.

**Comment by slc1973** [comment]
I'm not 100% sure, but looks like changes must be requested to CLDR project via Survey Tool: https://sites.google.com/site/cldr/translation

Here you can see what's is wrong: https://st.unicode.org/cldr-apps/v#/ru/Gregorian/

**Comment by mosuem** [comment]
The above comment is correct, the behavior is in line with the CLDR data, which is the source of truth for this repository.
