### ISSUE TITLE
Incorrect date parsing using 2-digit year pattern

### ISSUE THREAD

**Issue by carlleeswanson** [dart-lang/intl#275]
Date parsing of strings with 2-digit years does not yield correct results. It returns '00' for the century digits, regardless of which 'y' pattern is specified to DateFormat. The DateFormat documentation indicates that parsing using the 'yy' pattern will process the the century digits based on year value -80/+20.

In trying to figure this out, I also noticed that the DateFormat documentation references a 'DateParse instance', but I can find no other reference to such a class. Is that an obsolete reference? It is very confusing, because the example date used with that particular reference does not match the rest of the example.

Sorry, I don't fully understand if this is an issue with DateFormat or an issue with DateTime.parse(). Please let me know if I should submit this issue in a different location.
I'm using:
intl: ^0.16.1
dart: 2.7.2
flutter: 1.12.13+hotfix.9

EXAMPLE:
The following code yields the same year output (0078) for all format patterns. The first two outputs should yield 1978 as the year. The last three yield 0078 as expected.

String dateString = '4/12/78'  
List<String> patterns = [  
  'MM/dd/yy',
  'M/dd/yy',
  'MM/dd/yyyy',
  'M/dd/yyyy',
  'yMd',
];
patterns.forEach((pattern) {
  String isoDate = DateFormat(pattern).parse(dateString).toIso8601String();
  print('input: $dateString   output: $isoDate   pattern: $pattern');
});

OUTPUT:
I/flutter (17971): input: 4/12/78   output: 0078-04-12T00:00:00.000   pattern: MM/dd/yy
I/flutter (17971): input: 4/12/78   output: 0078-04-12T00:00:00.000   pattern: M/dd/yy
I/flutter (17971): input: 4/12/78   output: 0078-04-12T00:00:00.000   pattern: MM/dd/yyyy
I/flutter (17971): input: 4/12/78   output: 0078-04-12T00:00:00.000   pattern: M/dd/yyyy
I/flutter (17971): input: 4/12/78   output: 0078-04-12T00:00:00.000   pattern: yMd

**Comment by johnneijzen** [comment]
got same problem today i dont know why it was working correctly two days ago

**Comment by johnneijzen** [comment]
![image](https://user-images.githubusercontent.com/1343960/80787461-343f5d80-8bb9-11ea-8d53-9e41b68b6bb7.png)

**Comment by johnneijzen** [comment]
i use hacked workaround from this #123 to fix it

**Comment by jlubeck** [comment]
This should probably be closed as duplicate of #123. Which has been fixed in master btw.

**Comment by carlleeswanson** [comment]
Agreed. Sorry I didn't find the dup before filing this one.
