### ISSUE TITLE
Safe way to remove a key

### ISSUE THREAD

**Issue by BizzottoClaudio** [dart-lang/intl#279]
I can't find the documentation on what is the best method the remove a key, or a command to remove all the unused keys. I'm using android studio and the flutter_intl plugin.

I've also asked [this same question](https://stackoverflow.com/questions/61497737/how-to-remove-unused-keys-in-flutter-intl) on stackoverflow but got no answers

**Comment by mosuem** [comment]
This is a Flutter question, from all I can tell; so please refile the issue there.
