### ISSUE TITLE
No decimal digits if decimal part is zero

### ISSUE THREAD

**Issue by ManuLpz4** [dart-lang/intl#284]
![carbon (14)](https://user-images.githubusercontent.com/17878459/81153605-740b9980-8f59-11ea-8a65-bccd43118e30.png)

I tried every possible pattern (I think) and it can't satisfy my need. Any suggestion? Please and thank you :)

**Comment by Sun3** [comment]
I also have a need for this feature.

**Comment by shantanu1k** [comment]
@ManuLpz4 it must have happened because of 'number 100' stored in double type variable.

**Comment by ManuLpz4** [comment]
@shantanu1k `NumberFormat.currency` always formats with decimals because it's the "proper way" but I don't like too much for the UI/UX.
I solved it this way to work with any currency :)

```dart
class Formatter {
  static String currency(double amount, Currency currency) {
    final NumberFormat numberFormat = NumberFormat.currency(
      symbol: currency.symbol,
      decimalDigits: currency.decimalDigits,
      customPattern: currency.pattern,
    );
    String formattedString = numberFormat.format(amount);

    if (amount % 1 == 0) {
      final List<String> parts = formattedString.split(' ');
      formattedString = parts.first.substring(
        0,
        parts.first.length - currency.decimalDigits - 1,
      );

      if (parts.length == 2) {
        formattedString = '$formattedString ${parts.last}';
      }
    }

    return formattedString;
  }
}

```
