### ISSUE TITLE
[Question] how to use another translation?

### ISSUE THREAD

**Issue by matanshukry** [dart-lang/intl#288]
I have these 2 messages:
- appName: pretty clear, the application name. Used in various places such as headers
- welcome: A welcome statement that should include the app name.

How does one combine these 2?

Option A: Duplicate the app name in the translation, and put it once in 'appName' on it's own, and once in 'welcome' where it needs to be.
Option B: Have the 'welcome' message get an argument, and in the app get the appName message, then pass it to the welcome message.

Option A sounds mostly terrible if you want to change the appName. While that may not happen frequently, this is just an example and I'm looking for a more guidelines/experienced question.

Option B sounds a bit better, but it feels weird to get a translation just to give it to another translation. I could be completely wrong though?

This is more of a guideline question since I'm not too familiar with translations in general, but I think it can also be benefit to other (probably new) people.

**Comment by mosuem** [comment]
stackoverflow.com or other forums might be better suited for this kind of general question, which is not limited to `package:intl` or even Dart.

I personally think there is nothing wrong with Option B.
