### ISSUE TITLE
First day of week incorrect for pt_BR locale

### ISSUE THREAD

**Issue by darrenaustin** [dart-lang/intl#291]
The Flutter Material Date Pickers depend on the `DateFormat.dateSymbols.FIRSTDAYOFWEEK` to determine the start day for the week shown in the date grid.  However, for the pt_BR locale this is returning Sunday. According to https://github.com/flutter/flutter/issues/57050 it should be Monday.

Specifically: 

```dart
DateFormat.yMMMMEEEEd('pt-BZ').dateSymbols.FIRSTDAYOFWEEK
```

returns 6 which maps to Sunday, when it should be 0 for Monday.

**Comment by mosuem** [comment]
The CLDR data, which is the source of truth for this repository, specifies
```
<firstDay day="sun"  territories="
	AG AS
	BD BR BS BT BW BZ
	CA CO
	DM DO
	ET
	GT GU
	HK HN
	ID IL IN
	JM JP
	KE KH KR
	LA
	MH MM MO MT MX MZ
	NI NP
	PA PE PH PK PR PT PY
	SA SG SV
	TH TT TW
	UM US
	VE VI
	WS
	YE
	ZA ZW"
/>
```
