### ISSUE TITLE
Unable to call initializeDateFormatting

### ISSUE THREAD

**Issue by flavio20002** [dart-lang/intl#292]
I'm following the documentation and calling:

`initializeDateFormatting('de_DE', null);`

but I'm getting the following exception:

Unhandled Exception: Invalid argument(s): join(null, "symbols"): part 0 was null, but part 1 was not.

intl version: 0.16.1
flutter version: 1.17.2

Thanks for helping me.

**Comment by alan-knight** [comment]
You are probably importing the wrong library that contains that function. There are different ones depending how you want to get the data, try date_symbol_data_local.dart. But in general, if you want a good answer you need to provide much more information.

**Comment by flavio20002** [comment]
Thanks, I was importing the wrong library 

`import 'package:intl/date_symbol_data_file.dart';`

I think this will be useful for somebody else.

**Comment by d-apps** [comment]
> Thanks, I was importing the wrong library
> 
> `import 'package:intl/date_symbol_data_file.dart';`
> 
> I think this will be useful for somebody else.

Same here, problem solved.
