### ISSUE TITLE
Wrong default currency for pt locale

### ISSUE THREAD

**Issue by romatallinn** [dart-lang/intl#296]
The pt locale, which corresponds to Portuguese, has a default currency of the Brazilian dollar. However, it would be far safer to leave it as the euro since Portugal is part of the European Union.

```
var format = NumberFormat.simpleCurrency(locale: 'pt');
print(format.currencyName);
```

Expected: `EUR`
Actual: `BRL`

**Comment by mosuem** [comment]
```
var format = NumberFormat.simpleCurrency(locale: 'pt_PT');
print(format.currencyName); // prints EUR
```

This is default behavior as per [CLDR data](https://cldr.unicode.org/translation/translation-guide-general/default-content):

> Portuguese (Brazil) [pt_BR] is the default content locale for Portuguese [pt].
