### ISSUE TITLE
Enable approach to use string as a key to get localized value.

### ISSUE THREAD

**Issue by Yke222** [dart-lang/intl#298]
On our project, the best approach in order to follow our architecture guidelines is to use keys to access the localized values, but this support is now manually achieved by the team, by following an approach that is close the the android API, we do the following change in order to access the values:

The following automated code:
```
{ 
 /// `Example`
  String get app_name {
    return = Intl.message(
      'Example',
      name: 'app_name',
      desc: '',
      args: [],
    );
 }
```

becomes:
```
{ 
 /// `Example`
  String get app_name {
    String message = Intl.message(
      'Example',
      name: 'app_name',
      desc: '',
      args: [],
    );

    map.putIfAbsent("app_name", () => message);

    return message;
  }
```
and the access is made by:
```
String localizedEntry(String entry) {
    if (map.containsKey(entry)) {
      return map[entry];
    } else {
      return "";
    }
  }
```
by initializing all strings when the application is opened.
```
void initialize() {
  app_name;
}
```

Please, change the current implementation in order to account for key values.

Thank you.

**Comment by alan-knight** [comment]
This is duplicating what the system is basically doing internally. To make an API like that, in a separate file, make a wrapper for Intl.message. Don't run that file through extract_messages, because it will complain that the message is malformed.

```
String localizedEntry(String messageName) => Intl.message('', name: messageName);
```

and in your program, call that.

```
String get someMessage => Intl.message('something', name: 'someMessage');

void main(List<String> arguments) async {
  await initializeMessages('fr');
  Intl.defaultLocale = 'fr';
  print(localizedEntry('someMessage'));
}

Note that just looking up by string will not work for messages that have parameters (most notably plurals, genders, etc).

**Comment by Yke222** [comment]
Found that a good way of working with this approach is by creating another class that looks the Intl.message by key, with the following convention:

`
String getElementLocalized(String key,
        {String description, List<Object> args}) =>
    Intl.message("", name: key, desc: description, args: args);
`

This enables us to pass the key value, and use without any problem.

**Comment by Hasankanso** [comment]
> Found that a good way of working with this approach is by creating another class that looks the Intl.message by key, with the following convention:
> 
> `String getElementLocalized(String key, {String description, List<Object> args}) => Intl.message("", name: key, desc: description, args: args);`
> 
> This enables us to pass the key value, and use without any problem.

Hey,

I'm trying your solution, and I'm getting an empty "" string back (the first argument of Intl.message(...)) and not the translation.
do you know what is the reason?

**Comment by AleksandarSavic95** [comment]
You can use the Select ICU format, like explained in [this StackOverflow answer](https://stackoverflow.com/a/62265299/2101117). 
Basically in your arb files you will have:
```
"myKeyValueOptions": "{varName, select, optionOne {translation of 1st option} secondOption {2nd option's translation} other {whatever doesn't get matched gives this text}}",
"@myKeyValueOptions": {
  "placeholders": {
    "varName": {}
  }
}
```

You can change the `varName`, but the word `select` after that 1st comma must stay `select`, that's the format.

**Comment by Navil** [comment]
Is there any updates on this or a recommended workaround to get a value dynamically?

Sounds like a basic feature to me.

**Comment by Hasankanso** [comment]
Workaround the whole library. Meaning, look for another package.
> Is there any updates on this or a recommended workaround to get a value dynamically?
> 
> 
> 
> Sounds like a basic feature to me.

**Comment by alanknight-wk** [comment]
The mechanism above (https://github.com/dart-lang/intl/issues/298#issuecomment-653602409) works fine.
