### ISSUE TITLE
DateFormat crashes on web

### ISSUE THREAD

**Issue by sergiocasero** [dart-lang/intl#299]
Hello guys, I'm trying to use `DateFormat` on web but is crashing because of null,

It's really really rare, this is the code:

```dart
var date = DateFormat("HH:mm").format(
      DateTime.now(),
)
print(date);
```

On Android and iOS works as expected, but on web...

```Another exception was thrown: Invalid argument: null```

Any help?

Flutter doctor:
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 1.19.0-4.3.pre, on Mac OS X 10.15.5 19F101, locale es-ES)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[✓] Connected device (2 available)

• No issues found!

**Comment by jamesderlin** [comment]
"Another exception was thrown" implies that there was a prior exception.  Was there?  Was there a stacktrace?  What is the full error output?

**Comment by mosuem** [comment]
Closing until we have more information.
