### ISSUE TITLE
Parsing datetimes that are just digits with no delimiters fails

### ISSUE THREAD

**Issue by alan-knight** [dart-lang/intl#3]
For example, '20150210195856'. The parsing logic just tries to find the next digits without regard to the length, so it pulls in too much data.

**Comment by alan-knight** [comment]
This is infeasible. It comes up a few times as wanting to parse a Date like 20150429, but that's not a good use of this library. This is for internationalization. If you want to read a hard-coded datetime format with fixed length fields you can do that much, much more efficiently. This expects to print the fields in many different ways depending on locale information, possibly not in the same order, and the field specifies are not interpreted literally. That is, MM does not necessarily mean a padded two digit date, so if there are no delimiters we really can't handle it.

**Comment by blevinstein** [comment]
For others looking for a solution to this, DateTime.parse provides this capability.
https://api.dartlang.org/stable/1.24.3/dart-core/DateTime/parse.html

**Comment by alan-knight** [comment]
Well that's interesting, I didn't realize that. Thanks for pointing it out.
