### ISSUE TITLE
Incorrect time conversation from 24hr to 12hr formate 

### ISSUE THREAD

**Issue by DhavalRKansara** [dart-lang/intl#300]
Try to convert 12:00:00 time into 12-hour formate and it will return 12:00 AM on behalf of 12:00 PM.

var currentTime = 12:00:00

Code: `DateFormat('hh:mm aaa').format(DateFormat("hh:mm:ss").parse('12:00:00')),`

**Comment by vishnu-r-nair** [comment]
@DhavalRKansara Were you able to fix it?

**Comment by iqfareez** [comment]
I'm also facing the same issue, but later found the solution in the [docs](https://api.flutter.dev/flutter/intl/DateFormat-class.html)
> For example, in an explicit pattern the letters 'H' and 'h' are available for 24 hour and 12 hour time formats respectively.

use `HH:mm` for 24 hour format & `hh:mm` for 12 hour.

**Comment by HemilTheRebel** [comment]
For people coming from future, I was trying to parse a 12 hour format into a DateTime.

```
final _dateFormat = DateFormat("dd-MM-yyyy HH:mm a")
_dateFormat.parse('01-04-2023 12:00 PM')
```

Was being parsed as 2nd April, 2023, 12:AM. 

Changing the format to `hh` fixed it. Fixed format - `DateFormat("dd-MM-yyyy hh:mm a")`
