### ISSUE TITLE
Plugin support for using modules within an IDE's project

### ISSUE THREAD

**Issue by oravecz** [dart-lang/intl#308]
I don't think this is directly related to #9. I am using IntelliJ and I have created a flutter "module" inside my "project". For example, the folder structure is like this.

    my_project/
      misc_folder/
      my_flutter_module/
        pubspec.yaml
        lib/
          generated/
          l10n/

I could only get the Tools menu to appear when I used IntelliJ to create the Flutter module. If I created the project using `flutter create`, it doesn't recognize that it is in a module and the menu does not appear under Tools menu.

When I go to use Add Locale it adds the ARB in the root of the project, not relative to the current module. When I go to remove a locale, it doesn't find it.

**Comment by mosuem** [comment]
This sounds more like a Flutter issue; please refile this there.
