### ISSUE TITLE
How to have a dynamic translation lookup table?

### ISSUE THREAD

**Issue by sceee** [dart-lang/intl#311]
I am having a Map where the value for each key (ID) must be localized.

Having my translations file contain stuff like
```
String get entry_408fb1c2044643eeb74652908b41b19c => Intl.message('Item X', name: 'entry_408fb1c2044643eeb74652908b41b19c');
String get entry_192320807c944c599d9a155d230effdc => Intl.message('Item Y', name: 'entry_192320807c944c599d9a155d230effdc');
...
```
is pretty hard to maintain for many many items because additionally - due to the fact that flutter does not support reflection, there cannot be any dynamic calls to that translation (`Translations.of(context).entry('192320807c944c599d9a155d230effdc')`) so every call needs to be hardly programmed by hand.

I already though about something like
```
String entry(String entryID) {
    switch (entryID) {
        case '408fb1c2044643eeb74652908b41b19c':
            return Intl.message('Item X, name: '...');
...
    }
}
```
but this does unfortunately not work because A: the method name needs to be the same as the Intl.message() `name` and B: the name must be unique (so just entry won't work).

Is there any way to be able to call a translation dynamically? If such translation does not exist, it should just return null.

**Comment by alan-knight** [comment]
This sounds like https://github.com/dart-lang/intl/issues/298

**Comment by sceee** [comment]
@alan-knight wonderful, thank you very much. The solution mentioned [here](https://github.com/dart-lang/intl/issues/298#issuecomment-658137958) works for me.
