### ISSUE TITLE
[intl][pedantic] pedantic strong mode throws errors in messages_<value>.dart files

### ISSUE THREAD

**Issue by WalnutIT** [dart-lang/intl#322]
**Precondition**

_pubspec.yaml_
```
dependencies:
   ...
   pedantic: ^1.9.2
```

_analysis_options.yaml_

```include: package:pedantic/analysis_options.yaml
analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
```

Hint: The file analysis_options has to be added into the root folder of a flutter project

**Execution**

```
flutter pub run intl_translation:extract_to_arb --output-dir=lib/l10n lib/locale/corporate_page_localizations.dart
```

**Result**

_messages_all.dart_

```
'de': () => new Future.value(null),
```

and the error message 

```
Missing type arguments for generic type 'Future<dynamic>'.  Try adding an explicit type, or remove implicit-dynamic from your analysis options file.
```

_messages\_\<language\>.dart_

```
final messages = _notInlinedMessages(_notInlinedMessages);
  static _notInlinedMessages( _) => <String, Function> {
```
and the error messages

```
Missing return type for '_notInlinedMessages'.  Try adding an explicit type, or remove implicit-dynamic from your analysis options file.
```

and

```
Missing parameter type for '_'.  Try adding an explicit type, or remove implicit-dynamic from your analysis options file.
```

**Possible Solution**

_messages_all.dart_

```
'de': () => new Future<String>.value(null),
```

_messages\_\<language\>.dart_

```
final messages = _notInlinedMessages(_notInlinedMessages);
  static Map<String, Function> _notInlinedMessages(Function _) =>
```
**My Request**

Would it be possible to add the types in order to avoid that people, which use the strong mode of pedantic, don't have to update the code manually everytime when running the `flutter pub run intl_translation:extract_to_arb` command.

Thank you very much in advance

**Comment by vaetas** [comment]
You can fix this for now by excluding generated files from the analysis.

```yaml
analyzer:
  exclude:
    - lib/generated/**
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
```

This should hide both *implicit-dynamic* error and possible lint warnings.
