### ISSUE TITLE
DateFormat parse overflows

### ISSUE THREAD

**Issue by feinstein** [dart-lang/intl#327]
Trying this:

```dart
DateFormat.Hm(languageTag).parse('26:78');
```

Results in `03:18` and not a `FormatException`.

The docs mention `parseStrict` for dates but not times, it would be nice to add a mention to time as well.

`parseStrict` gets the error for '26:78', but if I use `23:66` instead:

```dart
DateFormat.Hm(languageTag).parseStrict('23:66');
```

It overflows to `00:06`.

There's no mention of overflowing in the docs and this behavior is AFAIK very undesirable.

**Comment by mosuem** [comment]
I cannot reproduce the overflowing, it throws a `FormatException` for me. Could you post the exact code which led to this error? Otherwise I assume this has been fixed since.
