### ISSUE TITLE
Support for `as` and `or` locales

### ISSUE THREAD

**Issue by shihaohong** [dart-lang/intl#341]
These locales are newly supported Android languages that were added in Android Pie. Flutter contains localized messages for these, but they are not usable since they aren't considered supported languages in the `intl` library.

**Comment by mehmetf** [comment]
@davidmorgan What's the process for this?

**Comment by davidmorgan** [comment]
Please file a bug and we'll figure it out :)

**Comment by mehmetf** [comment]
b/173391132
