### ISSUE TITLE
Get wrong days of the week

### ISSUE THREAD

**Issue by TolgaYld** [dart-lang/intl#344]
Hello,

from monday to thursday, i get the right days, but from friday, i get the wrong days. Why?

Code example: 

```
Text(
                                            DateFormat('EEEE').format(
                                                DateTime(DateTime.friday)),
                                          ),
```

and i get saturday....

**Comment by alanknight-wk** [comment]
Because the year 4 was a leap year. You're not doing what you think.

**Comment by TolgaYld** [comment]
> Because the year 4 was a leap year. You're not doing what you think.

What does the leap year have to do with the weekday?

**Comment by Ahmadre** [comment]
> > Because the year 4 was a leap year. You're not doing what you think.
> 
> What does the leap year have to do with the weekday?

`DateTime` constructor is expecting the "year" as the first parameter. So that's why

**Comment by mosuem** [comment]
Just for completeness, the correct way to get the weekdays would be
```
var locale = "in";
var weekdays = DateFormat("", locale).dateSymbols.WEEKDAYS; // or SHORTWEEKDAYS etc.
```
