### ISSUE TITLE
Issue after upgrading Flutter.

### ISSUE THREAD

**Issue by venkatsnag** [dart-lang/intl#350]
Getting this error,

The current Dart SDK version is 2.12.0-141.0.dev.

Because intl_translation <0.17.0 requires SDK version >=1.12.0 <2.0.0 and intl_translation >=0.17.0 <0.17.7 depends on intl ^0.15.3, intl_translation <0.17.7 requires intl ^0.15.3.
And because intl_translation >=0.17.7 depends on intl >=0.15.3 <0.17.0, every version of intl_translation requires intl >=0.15.3 <0.17.0.
So, because SmartFarmz depends on both intl ^0.17.0-nullsafety.2 and intl_translation any, version solving failed.

Seems like this package should be compatible with new dart version? any work arounds?

**Comment by armaganX** [comment]
Switch flutter channel to stable, then you can use intl: ^0.16.1

**Comment by alexmarkley** [comment]
This issue has now escalated to a blocker on Flutter stable following the 2.0.0 release. Many of us are having to use `flutter downgrade` to roll back to a working environment for our projects.

**Comment by a-leblond** [comment]
> 
> 
> This issue has now escalated to a blocker on Flutter stable following the 2.0.0 release. Many of us are having to use `flutter downgrade` to roll back to a working environment for our projects.

I can confirm, i can't build on Flutter stable since the 2.0 release : 

`Because intl 0.17.0 requires SDK version >=2.12.0-0 <3.0.0 and no versions of intl match >0.17.0 <0.18.0, intl ^0.17.0 is forbidden.`
