### ISSUE TITLE
Unable to parse valid date after setting locale to de_DE

### ISSUE THREAD

**Issue by trueToastedCode** [dart-lang/intl#353]
Executed before:
```
await initializeDateFormatting("de_DE", null);
Intl.defaultLocale = "de_DE";
```
Format set to `"dd. MMM hh:mm yyyy"`
This works.
`Date 1: "16. Mai 19:30 2010"`
This fails?
`Date 2: "16. Jan 20:16 2021"`
`Unhandled Exception: FormatException: Trying to read MMM from 16. Jan 20:16 2021 at position 4`

**Comment by alan-knight** [comment]
That locale data wants a period for month names that are abbreviations. So
"Jan."
https://github.com/dart-lang/intl/blob/master/lib/date_symbol_data_local.dart#L2695

**Comment by trueToastedCode** [comment]
This works... thanks 👍
