### ISSUE TITLE
TextField with initial value, wrong format until input anything

### ISSUE THREAD

**Issue by omerrciftcii** [dart-lang/intl#354]
Thank you for this great package, I am using this very efficient way. However I have problem with initial value of TextFields. Data is coming from service, so I have to set initial value to textfield according to coming value. Phonenumber is coming as expected(not with symbols like "-" ," ") but, it can't pass validation until I trigger onChanged method to textfield. For example if I try to write something to text field, it being validated automatically, and symbols added succesfully.

**Comment by mosuem** [comment]
This sounds like a Flutter problem, please consider asking this on [stackoverflow.com](https://stackoverflow.com/) or similar forums.
