### ISSUE TITLE
Flutter 2.0.1 stable channel

### ISSUE THREAD

**Issue by jrcollin** [dart-lang/intl#369]
the Intl  0.17.0 code generator generates code that does not compile. (dart sdk: ">=2.12.0 <3.0.0") it seems that generated files are not null safe.

Error message:
Lib/generated/intl/messages_all.dart:34:14: Error: The value 'null' can't be returned from a function with return type 'MessageLookupByLibrary' because 'MessageLookupByLibrary' is not nullable.
 - 'MessageLookupByLibrary' is from 'package:intl/message_lookup_by_library.dart' ('/C:/Users/jeanr/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/intl-0.17.0/lib/message_lookup_by_library.dart').
      return null;

**Comment by mrcsilva** [comment]
Also in the file `l10n.dart` the following errors are generated: 

1. For the code `S();`: 
    - Non-nullable instance field 'current' must be initialized. (not_initialized_non_nullable_instance_field at lib/generated/l10n.dart:16) 
2. For the code `static S current;`
    - The non-nullable variable 'current' must be initialized. (not_initialized_non_nullable_variable at lib/generated/l10n.dart:18)
3. For the code `return Localizations.of<S>(context, S);`
    - A value of type 'S?' can't be returned from the method 'of' because it has a return type of 'S'. (return_of_invalid_type at lib/generated/l10n.dart:35)

**Comment by lzoran** [comment]
Hi @jrcollin, @mrcsilva,

According to the generated code, I assume that these issues are related to the [intl_utils](https://github.com/localizely/intl_utils) package 😕.

If that is the case, you can solve this by upgrading the `intl_utils` package to the `2.1.0` version.
In case that you are using [Flutter Intl extension](https://marketplace.visualstudio.com/items?itemName=localizely.flutter-intl) for VS Code or [Flutter Intl plugin](https://plugins.jetbrains.com/plugin/13666-flutter-intl) for Android Studio, just upgrade them to the latest version.

Hope it helps!

**Comment by mrcsilva** [comment]
Hi @lzoran,

Thanks for your help! After updating Flutter Intl plugin for Android Studio/IntelliJ the generation changed and error messages were gone.

**Comment by jrcollin** [comment]
Hi @lzoran,
Thanks a lot for your help, effectively it works. I am a little confused about which package does what..
