### ISSUE TITLE
Add new Locale for latin American Spanish

### ISSUE THREAD

**Issue by herrmonkey** [dart-lang/intl#371]
Hi guys

I'm working on a Flutter App, and my intend is cover latin american spanish but when try to set the new locale as 'es_419', give me an error, but if I set es_CO (Colombia), this works fine

![Captura de pantalla 2021-03-16 a las 4 03 57 p  m](https://user-images.githubusercontent.com/41550237/111379507-385d5800-8671-11eb-8ff1-2c18ab1aea48.png)

Is an error, or I'm doing something wrong?

Thanks

**Comment by lzoran** [comment]
Hi @herrmonkey,

Maybe I'm wrong, but according to the posted screenshot, this issue may be related to the [Flutter Intl plugin](https://github.com/localizely/flutter-intl-intellij) for Android Studio.

If that is the case, could you please upvote the [issue](https://github.com/localizely/flutter-intl-intellij/issues/63) so we can know the demand for this functionality?

**Comment by herrmonkey** [comment]
Sure Thanks!
