### ISSUE TITLE
No constructor for millisecond in Intl package.

### ISSUE THREAD

**Issue by Yuvaraj-Gajaraj** [dart-lang/intl#385]
Hi Team,

When  I try to convert the following Datetime to the millisecond format there is no constructor in `Intl` package, So I have used the following method to get the millisecond format from the given value,
```
final format = DateFormat('ss.SSS');
String millisecond =  format.format(DateTime.fromMillisecondsSinceEpoch(timeStamp));
```
In the future are you going to provide constructor support for a millisecond or we can use this method to achieve this?

**Comment by mosuem** [comment]
I suppose you would want a `DateFormat.format` method which accepts UNIX timestamps; there is no plan currently to support this. If you are unhappy with your current solution, please reopen this ticket. I personally think your code looks fine as is, and internally the same kind of code would be called.
