### ISSUE TITLE
How to support different regions of the same language at the same time?

### ISSUE THREAD

**Issue by lizhuoyuan** [dart-lang/intl#386]
I want to use the same copy for different regions in the same language.

For example, I have a “zh” file.
I hope that when the user's locale is 'zh_CN' or 'zh_HK', this language file can be automatically loaded.

Now, when the locale is 'zh_CN' or 'zh_HK', it returns the default language

**Comment by mosuem** [comment]
I assume this is resolved; if not, please reopen.
