### ISSUE TITLE
[QUESTION] Extract message functions to another file

### ISSUE THREAD

**Issue by kauzige** [dart-lang/intl#387]
Is there a way to extract the message functions from the S class and put them in another file?

This so you don't have many lines of code and this way you have the main class initialising the language and another class that only contains the functions to call them.

**Comment by mosuem** [comment]
What is the S class? Please add some more information to help resolve this issue. If this is about the [Flutter internationalization workflow](https://docs.flutter.dev/development/accessibility-and-localization/internationalization), please consider opening an issue there.

If you want to organize all calls to `Intl.message` to a separate class, I see no reason why this should not work.
