### ISSUE TITLE
Enforce prefix sign possible?

### ISSUE THREAD

**Issue by IanWorthington** [dart-lang/intl#389]
I'm trying to figure out how to enforce a prefix +/- sign.

These seems to require setting the variable positivePrefix, but I can't work out if it's possible to do that from the constructor or not.

**Comment by mosuem** [comment]
```
import 'package:intl/intl.dart';

void main() {
  var numberFormat = NumberFormat('+#;-#');
  print(numberFormat.format(10)); // prints +10
  print(numberFormat.format(-10)); // prints -10
}

```

Here, `;` acts as the `PATTERN_SEPARATOR`, which allows you to first specify the positive and then the negative prefix.

If this does not answer your question, please reopen this issue.
