### ISSUE TITLE
Unable to use bm_ML locale

### ISSUE THREAD

**Issue by mustakimpawle** [dart-lang/intl#394]
I'm building the app for Bambara Mali users but not able to get currency in the local symbol.

My code to get currency with symbol:
`String moneyFormatter(String value) {
  if (value == null || value == '') return '';  
return NumberFormat.simpleCurrency(decimalDigits: 2, locale: 'en_US')
      .format(double.parse(value));
}`

Pubspec.yaml file:
`intl: ^0.16.1`

Error:
**Invalid locale**

Reference of Locale:
https://pub.dev/documentation/locales/latest/locales/Locale/bm_ML-constant.html

Thank you.

**Comment by mosuem** [comment]
Closing in favor of #414
