### ISSUE TITLE
flutter_gen incompatibility

### ISSUE THREAD

**Issue by Leptopoda** [dart-lang/intl#395]
Hi there,
when using the [flutter_gen](https://pub.dev/packages/flutter_gen) package intl stops working.

**Comment by pezi** [comment]
For date format handling the import
`import 'package:intl/intl.dart' as intl;`
is missing inside the language file
`.dart_tool\flutter_gen\gen_l10n\app_localizations_de.dart`
and therefore the build fails, if you use code like this.

```
  "dateTimeToday": "Today, {dateTime}",
  "@dateTimeToday": {
    "description": "Shows that the timestamp is from earlier today, similar to email programs",
    "placeholders": {
      "dateTime": {
        "type": "DateTime",
        "format": "Hm"
      }
    }
  }
```

**Comment by Leptopoda** [comment]
So I've solved my problem (used `flutter_gen` instead of `flutter_gen_runner`)
closing this one. @pezi  just open a new issue if you still have problems as it will probably be something different then
