### ISSUE TITLE
Feature request: Thousands in constructor

### ISSUE THREAD

**Issue by idkq** [dart-lang/intl#399]
Say I want to print both 1,000.00 and 1000.00 (no currency symbol)

I can hack currency:

`NumberFormat.currency(decimalDigits: 2, symbol: '').format(1000); //output 1,000.00`

but cannot

`NumberFormat.currency(decimalDigits: 2, symbol: '', thousands:false ).format(1000);`

**Comment by mosuem** [comment]
The `customPattern` argument should provide what you need. For example
```
var numberFormat = NumberFormat.currency(customPattern: '#.##');
print(numberFormat.format(1000)); //prints 1000.00
print(numberFormat.format(1000.10));  //prints 1000.10
print(numberFormat.format(1000.02)); //prints 1000.02
print(numberFormat.format(1000000)); //prints 1000000.00
```
