### ISSUE TITLE
How to make intl to generate dart files with null safety?

### ISSUE THREAD

**Issue by costacoz** [dart-lang/intl#408]
Flutter package `intl: 0.17.0-nullsafety.2` still generates dart files that don't follow null safety practices. I also tried adding this with no success:

```
dependency_overrides:
  intl: 0.17.0-nullsafety.2
```
It still generates folder without null safety.

How to force intl package to generate null safety dart files?

**Comment by MohammadEzoo** [comment]
using  intl: 0.17.0-nullsafety.2 without overriding solve the issue with me.

**Comment by costacoz** [comment]
In the end turned out the Intl plugin in Android Studio was outdated. After update, everything started working OK.
