### ISSUE TITLE
Locale data has not been initialized

### ISSUE THREAD

**Issue by MohamedAbd0** [dart-lang/intl#410]
Locale data has not been initialized, call initializeDateFormatting(<locale>).
after adding 
Intl.defaultLocale = 'ar';
intl: ^0.17.0

![Screen Shot 2021-06-21 at 2 36 26 AM](https://user-images.githubusercontent.com/32939129/122693285-8322d900-d239-11eb-89f5-083b72517c2f.png)

**Comment by mohamedelashry** [comment]
use this 
import 'package:intl/date_symbol_data_local.dart';
initializeDateFormatting('fr_FR', null).then((_) => runYourCode());
