### ISSUE TITLE
How to give support of internationalisation and localizations in flutter-sdk?

### ISSUE THREAD

**Issue by hiashutoshsingh** [dart-lang/intl#420]
Is there any way we can give support to internationalisation and localization in flutter-SDK?

The main and obvious problem is that there is no MaterialApp to wrap with to pass values to `supportedLocales`, `locale` and `localizationsDelegates`, and even if we wrap that in your App in which we are using SDK, then how to access arb files in the package?

Please let me know, how can I solve this problem.
Thanks!

**Comment by mosuem** [comment]
I am not quite sure what your use case is - could you elaborate? In general, the [intl_translation](https://github.com/dart-lang/intl_translation) package workflow needs no `MaterialApp`. 

Please reopen with more details if this doesn't solve your problem!
