### ISSUE TITLE
After getting system locale, 12-hour time formatting appears to break

### ISSUE THREAD

**Issue by jamesncl** [dart-lang/intl#421]
If I configure Intl to get the user's locale, by calling `await findSystemLocale()`, and then try to print the time using `DateFormat.jm()` (AM / PM format), it shows as 24 hour format. According to the docs, `DateFormat.jm()` should show AM / PM. For example:

```
import 'package:intl/intl.dart';
import 'package:intl/intl_standalone.dart';

...

await findSystemLocale();
final now = DateTime.now();
print("${Intl.systemLocale} ${DateFormat.jm().format(now)} ${DateFormat.Hm().format(now)}");
```

gives this (my locale is UK, i.e. en-GB):

> en_GB 18:19 18:19

If I don't use `await findSystemLocale()`, it correctly prints 12-hour time, but using the default locale (which appears to be en-US) instead of the user's actual locale:

> en_US 6:19 PM 18:19

Am I missing something, or is this a bug? I'm using `Intl 0.16.1`

**Comment by leifcr** [comment]
I'm seing a similar bug, when locale is set to Norwegian. I think Dateformat.jm should always return a 12H clock.
As for AM/PM view, that should probably follow the locale.
A workaround:
``` DateFormat('h:mm a').format(DateTime.now) 
```

**Comment by mosuem** [comment]
As I wrote in #455, ICU specs say
> Constant for date skeleton with hour and minute, with the locale's preferred hour format (12 or 24).

So this is more of a documentation issue. Locales which normally use a 24h format will have the same output for `Hm` and `jm`.
