### ISSUE TITLE
Plurals using "one" not parsed, only "=1", Localizely generated files don't work properly

### ISSUE THREAD

**Issue by alexobviously** [dart-lang/intl#422]
So Localizely generates entries like this:

```json
"people": "{count, plural, zero{} one{Person} other{People}}",
  "@people": {
    "placeholders": {
      "count": {}
    }
  },
```

and if I use that with `intl`, then I get generated code like this:

```dart
@override
String people(int count) {
  return intl.Intl.pluralLogic(
    count,
    locale: localeName,
    other: 'People',
  );
}
```

Note that it's missing the `one` field.

On the other hand, if I use this format:

```json
"people": "{count, plural, =1{Person} other{People}",
  "@people": {
      "description": "",
      "placeholders": {
          "count": {}
      }
  },
```

it works fine, generating this code:

```dart
@override
String people(int count) {
  return intl.Intl.pluralLogic(
    count,
    locale: localeName,
    one: 'Person',
    other: 'People',
  );
}
```

It would be really nice if this package could understand this format. Right now I have to manually edit every arb file that Localizely creates, and that's really not scalable. Unless I'm mistaken, this format does seem to be part of the arb specification, so it should work - I assume this is a bug?

**Comment by alan-knight** [comment]
The parsing would be in [intl_translation](https://github.com/dart-lang/intl_translation), not this package. And it should understand "one", at least it's in the [grammar](https://github.com/dart-lang/intl_translation/blob/master/lib/src/icu_parser.dart#L41). So there's probably something more complicated going on. Note that it's possible to add your own parsing if you need to work around issues or use a different format. See [intl_translation_format](https://github.com/jamesblasco/intl_translation_format).

**Comment by aleksakrstic** [comment]
Here is the issue I created for Flutter repo: https://github.com/flutter/flutter/issues/84291

**Comment by alan-knight** [comment]
Yes, but I don't think that's the same issue. See also https://github.com/dart-lang/intl/issues/139

**Comment by alexobviously** [comment]
> The parsing would be in [intl_translation](https://github.com/dart-lang/intl_translation), not this package. And it should understand "one", at least it's in the [grammar](https://github.com/dart-lang/intl_translation/blob/master/lib/src/icu_parser.dart#L41). So there's probably something more complicated going on. Note that it's possible to add your own parsing if you need to work around issues or use a different format. See [intl_translation_format](https://github.com/jamesblasco/intl_translation_format).

I'm not using intl_translation, I'm only using intl with the `flutter: generate: true` option and a `l10n.yaml`

**Comment by mosuem** [comment]
Closing in favor of #139 and/or the flutter issue.

**Comment by alexobviously** [comment]
This has been an annoyance for one of my projects for over a year now, hope
it can get fixed soon. It's worth noting that a major third party
translation tool, Localizely, exports arb files that depend on this, and as
such I have to manually process each file I get back from it, every time we
update translations.
