### ISSUE TITLE
How to localise a package (no MaterialApp)

### ISSUE THREAD

**Issue by GZaccaroni** [dart-lang/intl#423]
I share some package between my apps, and I need to have some texts in those packages localised, how can I do that since there is no MaterialApp in those packages?

**Comment by mosuem** [comment]
Please take a look at the workflow described in [package:intl_translation](https://github.com/dart-lang/intl_translation) - this does not require a `MaterialApp`.

It basically requires writing your to-be-translated messages as `Intl.message` calls, which can be extracted using `intl_translation:extract_to_arb` to generate an arb file. This file can be translated, and the translated `arb` files are used as input to run the `intl_translation:generate_from_arb` script to generate Dart files encoding the translation.

Please reopen if this does not solve your problem!
