### ISSUE TITLE
DateFormat.y() leaves separation dot in result

### ISSUE THREAD

**Issue by dvittore** [dart-lang/intl#424]
When DateFormat.y() is used strange behavior is experienced.

When locale of device is en-us, DateFormat.y().format(DateTime.now()) returns "2021" as expected.
However, when the locale of the device is hu - and date is formatted like 2021.09.17. - the return of the above function is "2021.".

There is an extra dot at the end, which causes unhandled exception, when trying to parse the above result as int.

**Comment by mosuem** [comment]
This seems to be consistent with how it should be according to the [CLDR data](https://st.unicode.org/cldr-apps/v#/hu/Generic/194595ec8420c908).

Please reopen if this is still unclear!
