### ISSUE TITLE
[QUESTION] - Any way to override certain symbols?

### ISSUE THREAD

**Issue by take** [dart-lang/intl#425]
Hi thanks for the awesome library!

I'm trying to override certain symbols for certain language, are there any ways to do this? 👀 

## e.g.

by updating `SHORTWEEKDAYS` in lib/src/data/dates/symbols/ja.json somehow...

```dart
DateFormat('M/d EEE', 'ja').format(DateTime.now())
=> "10/7 THU"
```

currently I would get

```dart
DateFormat('M/d EEE', 'ja',).format(DateTime.now())
=> "10/7 木"
```

**Comment by mosuem** [comment]
As these files are automatically generated from Unicode CLDR data, I don't think this is possible. I would suggest to simply replace them yourself afterwards by using 'String.replace', as there is no locale with `THU` as a `SHORTWEEKDAYS` entry.

**Comment by mosuem** [comment]
Thanks @alan-knight, I did not know about this!

If this does not solve the problem, please reopen this issue @take.
