### ISSUE TITLE
Date formatter issue

### ISSUE THREAD

**Issue by Ankit0080** [dart-lang/intl#435]
Atleast provide some working samples

**Comment by Ayush13Bhatia** [comment]
Add Null Safety In DateFormat.

Before:-  

String format(DateTime date) {
    // TODO(efortuna): read optional TimeZone argument (or similar)?
    var result = StringBuffer();
    for (var field in _formatFields) {
      result.write(field.format(date));
    }
    return result.toString();
  }

After:- 

 String format(DateTime? date) {
    // TODO(efortuna): read optional TimeZone argument (or similar)?
    var result = StringBuffer();
    for (var field in _formatFields) {
      result.write(field.format(date!));
    }
    return result.toString();
  }

**Comment by mosuem** [comment]
What exactly is the issue here? Please reopen if necessary.
