### ISSUE TITLE
DateFormat inconsistency

### ISSUE THREAD

**Issue by ky1vstar** [dart-lang/intl#445]
I'm trying to parse date string that looks like this `Feb0920221500` (month, day in month, year, hours, minutes). But when I use `MMMddyyyyHmm` pattern I always get a `FormatException`. Furthermore `intl`'s `DateFormat` fails to parse back a date which it has formatted before:

```dart
import 'package:intl/intl.dart';

void main() {
  final dateFormat = DateFormat("MMMddyyyyHmm"); // MMMddyyyyHHmm leads to the same result
  final dateString = dateFormat.format(DateTime.now());
  print(dateString);
  final date = dateFormat.parse(dateString);
  print(date);
}
```

Output:
```
Feb0920221511
Uncaught Error: FormatException: Trying to read yyyy from Feb0920221511 at position 13
```

What am I doing wrong?

`intl` package version: 0.17.0

<details>
  <summary>flutter --version</summary>

  ```
  Flutter 2.8.1 • channel stable • https://github.com/flutter/flutter.git
  Framework • revision 77d935af4d (8 weeks ago) • 2021-12-16 08:37:33 -0800
  Engine • revision 890a5fca2e
  Tools • Dart 2.15.1
  ```

</details>

**Comment by ky1vstar** [comment]
Okay, seems like a duplicate of https://github.com/dart-lang/intl/issues/210 and https://github.com/dart-lang/intl/issues/278. Pity it's still relevant

**Comment by natebosch** [comment]
Closing in favor of #210

**Comment by mosuem** [comment]
Reopening as this is slightly different from #210 

A `FixedDateTimeFormatter` in [package:convert](github.com/dart-lang/convert) - does this solve the issue? This issue is a bit different as it seems to use month 3(?) letter abbreviations. It could be possible to add another character there for this, or just replace the strings yourself:
```
String s = 'Feb0920221500';
  <String, String>{
    'Jan': '01',
    'Feb': '02',
    'Mar': '03',
    'Apr': '04',
    'May': '05',
    'Jun': '06',
    'Jul': '07',
    'Aug': '08',
    'Sep': '09',
    'Oct': '10',
    'Nov': '11',
    'Dec': '12',
  }.forEach((key, value) => s = s.replaceFirst(key, value));
```
