### ISSUE TITLE
German date format

### ISSUE THREAD

**Issue by gambanishu** [dart-lang/intl#451]
Germany is observing ISO 8601 through DIN 5008 since 1996 if I'm not mistaken.
`initializeDateFormatting();
var dateFormat = DateFormat.yMd('de');
print(dateFormat.format(DateTime.now()));`

produces: 24.2.2022
expected: 2022-02-24

**Comment by Namli1** [comment]
In 2001, the format dd.mm.yyyy was permitted again, see [here](https://de.wikipedia.org/wiki/DIN_5008#Änderungen_2001) (only in German, sorry 😅). It is also the more commonly used format in Germany, so I think it's okay to keep it like that.

**Comment by mosuem** [comment]
The newest [CLDR data](https://cldr.unicode.org/index/downloads) also specifies `d.M.y` as the `yMd` format for German - this seems to be correct. Please reopen if you have any more concerns!

**Comment by gambanishu** [comment]
I can't reopen it, have no privilege.

About the dd.mm.yyyy format permitted in 2001... The text says: "wenn keine Missverständnisse zu erwarten sind". With this format misunderstanding is always expected (as 01.02.2022. can be interpreted as 1st of February or 2nd of January), this is the nature of this format, and that's why the standard ISO format was rolled out.
About what is "more commonly used" and CLDR: about formats in Germany the Deutsches Institut für Normung is the only authoritative organization. Other bodies or what is more common has no significance. yyyy-mm-dd is a superior format, orders properly, internationally used and unambiguous. The way forward is to support it.

**Comment by mosuem** [comment]
Interesting ambiguity. I would recommend the Unicode CLDR data as the source of truth, which, as far as I understand it, does not use the ISO 8601 format. I suggest you file a bug [there](https://github.com/unicode-org/cldr/blob/main/docs/requesting_changes.md). A solution for the Dart case would be to use a custom format, or just the `DateTime.parse` method, which supports ISO 8601.
