### ISSUE TITLE
Possibility to display 12-hour format for de locale

### ISSUE THREAD

**Issue by solkaz** [dart-lang/intl#455]
If the locale is set to `de`, I cannot display the time in 12-hour format like so:

```dart
DateFormat('jm', 'de').format(DateTime.now())
```

While I realize that Germany mostly uses the 24-hour format, I would like to offer the possibility to display the time in the 12-hour format. If I change my settings in Android to German, it _is_ possible to use the 12-hour format.

**Comment by mosuem** [comment]
Even if there are not many use cases, offering this possibility sounds reasonable.

**Comment by mosuem** [comment]
Revisiting this, I would rather not implement it. The ICU spec says about the `jm` format:
> Constant for date skeleton with hour and minute, with the locale's preferred hour format (12 or 24).
Which would make it the same as `Hm` for the `de` locale. Setting the locale to `en_DE`, which internally falls back to `en`, resolves the issue.
