### ISSUE TITLE
How to make intl to generate dart files with null safety?

### ISSUE THREAD

**Issue by wanedenis** [dart-lang/intl#456]
My project was worked fine till yesterday.

 Flutter package intl: 0.17.0 still generates dart files that don't follow null safety practices. 
 
 This is the error i get when i try to build the app.
 
 lib/generated/l10n.dart:18:12: Error: Field 'current' should be initialized because its type 'S' doesn't allow null.
 - 'S' is from 'package:fstore/generated/l10n.dart' ('lib/generated/l10n.dart').
  static S current;
           ^^^^^^^
lib/generated/l10n.dart:35:26: Error: A value of type 'S?' can't be returned from a function with return type 'S' because 'S?' is nullable and 'S' isn't.
 - 'S' is from 'package:fstore/generated/l10n.dart' ('lib/generated/l10n.dart').
    return Localizations.of<S>(context, S);
                         ^
lib/generated/intl/messages_all.dart:223:36: Error: The value 'null' can't be returned from a function with return type 'MessageLookupByLibrary' because 'MessageLookupByLibrary' is not nullable.
 - 'MessageLookupByLibrary' is from 'package:intl/message_lookup_by_library.dart' ('../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/intl-0.17.0/lib/message_lookup_by_library.dart').
  if (actualLocale == null) return null;
 

dependency:
  intl: 0.17.0
It still generates folder without null safety.

How to force intl package to generate null safety dart files?

**Comment by lzoran** [comment]
According to the posted code, I assume that you are using the Flutter Intl plugin to generate localization code.

If that is the case, maybe responses from a similar [issue](https://github.com/localizely/flutter-intl-intellij/issues/76) might help.

Hope it helps!
