### ISSUE TITLE
DateFormat return invalid time format when using separator

### ISSUE THREAD

**Issue by bagus-repository** [dart-lang/intl#458]
On version `0.17.0` Using `DateFormat('H:m:s').format(DateTime.parse('2021-03-31 01:01:00'))` see `:` separator or you can just change it to anoother, will return 1:1:0 but when using Hms format without any separators It will return correct format 01:01:00

Long before I was using `0.16.0` it did not happen, is this current version behavior ?

Flutter 2.8.1
intl: 0.17.0

**Comment by natebosch** [comment]
The pattern `Hms` in the en_us locale corresponds to `HH:mm:ss`. Use double letters if you want to zero pad to 2 digits.

> Long before I was using `0.16.0` it did not happen, is this current version behavior ?

It should have behaved the same in `0.16.0`. I certainly can't produce a behavior difference.

https://pub.dev/documentation/intl/latest/intl/DateFormat-class.html#:~:text=if%20%27m%27%20produces%20%276%27%2C%20%27mm%27%20produces%20%2706%27
