### ISSUE TITLE
Unsupported locale 'fur_Latn_IT'

### ISSUE THREAD

**Issue by AdrienAudouard** [dart-lang/intl#463]
The locale `fur_Latn_IT` is not supported by Dart but it's a valid locale.

How to reproduce:
```Dart
import 'package:intl/intl.dart'; // for date format

void main() {
  NumberFormat.currency(locale: 'fur_Latn_IT').format(2.3);
}
```

The output:
```
Uncaught Error: Invalid argument(s): Invalid locale "fur_Latn_IT"
```

I know it's a tricky one but a few user has this crash on our App.

**Comment by nohli** [comment]
@AdrienAudouard is it a language or dialect?

Sounds like https://github.com/dart-lang/intl/issues/359.

**Comment by AdrienAudouard** [comment]
I think it's a dialect

**Comment by nohli** [comment]
> I think it's a dialect

In my case it's also a dialect.
