### ISSUE TITLE
Cannot format a number using decimal comma

### ISSUE THREAD

**Issue by nicolasvahidzein** [dart-lang/intl#464]
This code works:
`var numFormat = NumberFormat('#,##0.##');`

This one produces an error which makes no sense to me:
`var numFormat = NumberFormat('#.##0,##');`

**Comment by mosuem** [comment]
A `NumberFormat` takes a `.` as a decimal separator, as specified by the [ICU](https://cldr.unicode.org/translation/number-currency-formats/number-and-currency-patterns). Therefore, your second example fails, as a decimal separator must appear after the grouping separator `,`. The pattern must not be localized, the formatting of a number in your locale automatically for you when specifying it!

**Comment by nicolasvahidzein** [comment]
@mosuem Hello Mosuem, sorry but your response was confusing.

French people use commas as a decimal seperator. I don't understand how i am supposed to achieve that with in dart using NumberFormat.

**Comment by mosuem** [comment]
The format pattern string is not localized - so always use the `.` as a decimal separator. To format a number in French, you would need to specify that locale in the constructor:
```
  var numFormat = NumberFormat('#,##0.##', 'fr');
  print(numFormat.format(1234.56)); //prints 1 234,56
```

**Comment by nicolasvahidzein** [comment]
ah ok gotcha, thanks. This is still not correct though, in french . is the thousand separator. How do we achieve that?
It should look like this: 1.234.567,89 and not 1 234 567,89

**Comment by mosuem** [comment]
The [Unicode data](https://unicode-org.github.io/cldr-staging/charts/latest/by_type/numbers.symbols.html#a1ef41eaeb6982d) specifies a space as the separator for French - this is used as the source of truth by this package.

**Comment by nicolasvahidzein** [comment]
ok i understand, thanks a lot.
