### ISSUE TITLE
Locale resets when using license page

### ISSUE THREAD

**Issue by ThexXTURBOXx** [dart-lang/intl#465]
When clicking on any package in the pre-defined license page (i.e. `showLicensePage` from `material/about.dart`), the locale resets to `en_US`.
This is because `_PackageLicensePageState` in `material/about.dart` overrides the current `Locale` locally.
However, this local change has global effects as well, which are unwanted in almost every case.

This is actually a big issue and should be inspected properly, I think

**Comment by natebosch** [comment]
This issue appears to be about some flutter code. https://github.com/flutter/flutter/blob/5ecc3f67047706e163894dddb99e55c46ae38120/packages/flutter/lib/src/material/about.dart#L222

I can't transfer this issue across orgs so I'll close for now and you can reopen at https://github.com/flutter/flutter/issues

When you reopen the issue please add more information and a reproduction case.

**Comment by ThexXTURBOXx** [comment]
As it turns out, this issue seems to be related to `intl_utils` rather than `intl` itself. Thanks for your infromation @natebosch!
For a follow-up on this, see here: https://github.com/localizely/intl_utils/issues/19 and https://github.com/localizely/intl_utils/pull/18
