### ISSUE TITLE
support of ICU number placeholder "#"

### ISSUE THREAD

**Issue by Eric-Guan-Z** [dart-lang/intl#476]
According to [ICU document](https://phrase.com/blog/posts/guide-to-the-icu-message-format/#DartFlutter), In a pluralized form message like

```
The film won {n, plural,
one {# award}
other {# awards}}
```
The special # symbol will display the given count in the active locale’s number system.

Currently it seems

`flutterw pub run intl_utils:generate`
will not replace # to the given number param.

For example:

`{number, plural, one {Temporarily inactive (# day left)} other {Temporarily inactive (# days left)}}`
will generate

```
  String InactiveDaysLeft(num number) {
    return Intl.plural(
      number,
      one: 'Temporarily inactive (# day left)',
      other: 'Temporarily inactive (# days left)',
      name: 'Events_MeetingRoom_InactiveDaysLeft',
      desc: '',
      args: [number],
    );
  }
```
And when using this message, flutter intl does not support this kind of feature either. If a number of 2 is passed to this massage, it will directly return

`Temporarily inactive (# days left)`
Does any one know this is by design or its because I did something wrong in practice?

**Comment by chenasraf** [comment]
If this is still relevant, not sure if this is a bug or not, but you can just use the placeholder instead of `#`. In your case, use:

```
{number, plural, one {Temporarily inactive ({number} day left)} other {Temporarily inactive ({number} days left)}}
```

**Comment by mosuem** [comment]
The syntax @chenasraf described is correct.

At least per the [ICU website](https://unicode-org.github.io/icu/userguide/format_parse/messages/), their document also uses the braces syntax. Also please note that plural and select support in the `arb` file format is marked as [experimental](https://github.com/google/app-resource-bundle/wiki/ApplicationResourceBundleSpecification#plural-and-gender-support), and may change with evolving ICU standards.
