### ISSUE TITLE
Swahili day of a week abbrev is wrong

### ISSUE THREAD

**Issue by TadashiCZ** [dart-lang/intl#477]
When using DateFormat.E(locale) with Swahili, the name of the days are not shortened. It uses long forms instead of J1, J2,...
Source for correct abbrevs: https://hist.hse.ru/data/2019/06/16/1485884965/21.%20Days,%20Months,%20and%20Dates%20in%20Swahili.pdf

**Comment by mosuem** [comment]
The source of truth for this repo is the [CLDR data](https://st.unicode.org/cldr-apps/v#/sw/Gregorian/140cf3a4c102803b), which takes the full length name. If you think the data is wrong, please file an issue there.
