### ISSUE TITLE
`compactCurrency` & `compactSimpleCurrency` ignoring `decimalDigits`

### ISSUE THREAD

**Issue by mrverdant13** [dart-lang/intl#489]
## Details

According to the [`NumberFormat.decimalDigits` property](https://pub.dev/documentation/intl/latest/intl/NumberFormat/decimalDigits.html) docs,

> **If this is not explicitly specified in the constructor, then for currencies we use the default value for the currency if the name is given, otherwise we use the value from the pattern for the locale.**
>
> So, for example, NumberFormat.currency(name: 'USD', decimalDigits: 7) will format with 7 decimal digits, because that's what we asked for. But NumberFormat.currency(locale: 'en_US', name: 'JPY') will format with zero, because that's the default for JPY, and the currency's default takes priority over the locale's default. NumberFormat.currency(locale: 'en_US') will format with two, which is the default for that locale.

Now, the `NumberFormat.compactCurrency` and `NumberFormat.compactSimpleCurrency` formatter constructors expose the `decimalDigits` field without special considerations in the docs and, thus, the behaviour is expected to be the same. However, that is not the case.

### Code snippet

```dart
const myNumber = 1234567890123.987654321;
final formatter = NumberFormat.simpleCurrency(
  decimalDigits: 2,
);
final myNumberString = formatter.format(myNumber);
print(myNumberString);
```

### Results

**Expected:** `$123.46B` (rounding)
**Actual:** `$123B`

## Related issues

- #348

**Comment by mosuem** [comment]
For me, this gives a different output, namely `$1,234,567,890,123.99`, see also the [dartpad](https://dartpad.dartlang.org/?id=1be372bab0fa795f93c6). There does seem to be a bug related to the number of digits, which you already linked to. Please re-open this issue if necessary.
