### ISSUE TITLE
An exception occurred while formatting the date

### ISSUE THREAD

**Issue by Dboy233** [dart-lang/intl#491]
The same time, but in a different format, an exception occurred during the conversion。

```dart

void main() {

  final _createFormat = DateFormat('yyyyMMddHHmmssSSS');
  final _createFormat2 = DateFormat('yyyy_MM_dd_HH_mm_ss_SSS');

  final timeStr = '20220905151222549';
  final timeStr2 = '2022_09_05_15_12_22_549';

  print("======");
  final parse2 = _createFormat2.parse(timeStr2);
  print(parse2);
  print("======");
  final parse = _createFormat.parse(timeStr);
  print(parse);
  print("======");

}

```

![image](https://user-images.githubusercontent.com/37604230/188580328-53a6f3b6-cee3-4fe4-b65d-45b32076c3c4.png)

**Comment by eximius313** [comment]
this PR is the remedy: https://github.com/dart-lang/intl/pull/457

**Comment by Dboy233** [comment]
> this PR is the remedy: #457

That's exactly what I need.  But there is no merger at the moment

**Comment by mosuem** [comment]
Closing, as this feature is now included in [package:convert](https://github.com/dart-lang/convert).
