### ISSUE TITLE
DateFormat does not correctly translate AM/PM for Hindi

### ISSUE THREAD

**Issue by TzviPM** [dart-lang/intl#502]
Code such as the following

```
DateFormat.yMMMd('hi').add_jm().format(
                DateTime.fromMillisecondsSinceEpoch(
                  1591052400000,
                  isUtc: true,
                ),
              )
```

Translates the time in Hindi as `11:00 pm`.

I created a DartPad with a reproduction here: https://dartpad.dev/?id=7e2fdc5cabd4fda108883c24629d8801

In flutter:

```
DateFormat.yMMMd('hi').add_jm().dateSymbols.AMPMS
```

Returns `[am, pm]`. My understanding is that the correct text should be रात्री. And it should place before the number. Like '11:00 PM' should be translated as 'रात्री ११ वाजता'.

Note, this also is what I get from Chrome's JavaScript console:

<img width="358" alt="Screenshot 2022-10-24 at 11 40 12 AM" src="https://user-images.githubusercontent.com/1950680/197567679-3f77fbb2-71b2-4a11-a6a3-34605bc962e2.png">

**Comment by mosuem** [comment]
I don't think this is a bug, the [CLDR data](https://st.unicode.org/cldr-apps/v#/hi/Gregorian/5c6d3896851453de) also has `am` and `pm` for Hindi.

Regarding the placement, placing the `pm` after the time seems also correct again according to the [CLDR data](https://st.unicode.org/cldr-apps/v#/hi/Gregorian/423df67a6daff073).
