### ISSUE TITLE
unsupported operation cannot modify unmodifiable map dateTimePatternMap

### ISSUE THREAD

**Issue by xqskzs** [dart-lang/intl#503]
```
localizationsDelegates: const [
            GlobalMaterialLocalizations.delegate,
            GlobalWidgetsLocalizations.delegate,
            GlobalCupertinoLocalizations.delegate,
          ],
          supportedLocales: const [
            Locale('zh','TW'),
            Locale('en','US'),
          ],
```
do this and write "initializeDateFormatting()" will cause this error : `unsupported operation cannot modify unmodifiable map dateTimePatternMap`

**Comment by mosuem** [comment]
This is related to #493 . To fix your issue, please add some more details, for example why you are calling `initializeDateFormatting` in the first place.

**Comment by xqskzs** [comment]
use 'initializeDateFormatting()' is to show calendar，"MaterialApp(localizationsDelegates: const [
            GlobalMaterialLocalizations.delegate,
            GlobalWidgetsLocalizations.delegate,
            GlobalCupertinoLocalizations.delegate,
          ],
          supportedLocales: const [
            Locale('zh','TW'),
            Locale('en','US'),
          ],)" do this is to solve show English menu when long press "TextField or TextFormField", The menu is show "Copy or Cut", but I want to it show "剪下 或 貼上" ,unable to resolve by intl.  so "GlobalMaterialLocalizations.delegate" and "initializeDateFormatting()" cause this error : unsupported operation cannot modify unmodifiable map dateTimePatternMap.

**Comment by xqskzs** [comment]
Hello, Is there any way to solve the problem?

**Comment by mosuem** [comment]
You shouldn't have to call `initializeDateFormatting`, as the Flutter localization already calls `initializeDateFormattingCustom` internally. Could you try removing the call to `initializeDateFormatting`?

**Comment by xqskzs** [comment]
If I remove it need to persuade the group leader, and other members may be use this fuction "initializeDateFormatting", if you can do some logic in the "initializeDateFormatting()" , GlobalMaterialLocalizations.delegate should do some thing, add one variable record，call to initializeDateFormatting judge the variable and never call "initializeDateSymbols(dateTimeSymbolMap);
  initializeDatePatterns(dateTimePatternMap);" . Thanks.

**Comment by mosuem** [comment]
This will be fixed in general, so I am closing this issue in favor of #493 . For a hotfix for you, delete the call to `initializeDateFormatting`.
