### ISSUE TITLE
formatter.parse('2000-4-27') creates date that is 2000-01-27

### ISSUE THREAD

**Issue by Tusshu** [dart-lang/intl#509]
`var formatter = DateFormat('y-m-d');
  var initDate = formatter.parse('2000-4-27');
  print(initDate);`

Date printed is 2000-01-27 00:04:00.000

**Comment by mosuem** [comment]
The character `m` means minute, `M` means month (see the [docs](https://pub.dev/documentation/intl/latest/intl/DateFormat-class.html)). You probably want `y-M-d` as a format string.
