### ISSUE TITLE
Pub release

### ISSUE THREAD

**Issue by mchudy** [dart-lang/intl#513]
Is there any planned pub release of this package? The last one 0.17.0 was published 22 months ago. I'm trying to implement a feature based on `MessageFormat` and I need fixes from this commit https://github.com/dart-lang/intl/commit/474467742e3b79281decd159fc029017e48aeec9 I would prefer not to depend on the master branch for a long time.

**Comment by mosuem** [comment]
Hi! 
Yes there is a release planned very soon, just pending an internal review of a small feature.

**Comment by mosuem** [comment]
Closing for PR #520.
