### ISSUE TITLE
Different code generated after running initialize

### ISSUE THREAD

**Issue by dgt-erik** [dart-lang/intl#529]
**Describe the bug**
Me and a collegue have the same IDE, same extentions and versions installed.
But Flutter intl generates different code in messages_all.dart

This is the code difference:
Generated by my collegue:
```
 'de': () => new SynchronousFuture(null),
  'en': () => new SynchronousFuture(null),
  'nl': () => new SynchronousFuture(null),
```
Generated by me:
```
  'de': () => new Future.value(null),
  'en': () => new Future.value(null),
  'nl': () => new Future.value(null),
```
we both constantly push the changes to git when generating / adding keys.
It is annoying because it generated more code changed then necessary.

This behavior changed and disappeared after i executed flutter Intl: Initialize.
The difference, he added Intl, i did not.
I cloned the repo and executed flutter pub get. and used "saving pubspec.yaml" to generate the files.

**To Reproduce**
```
Create a project etc, add intl according to install.
Run Flutter Intl: initialize as described.
commit and push to repository

Clone repository on different computer
Run "flutter pub get"
Add a key in arb file
add space to pubspec.yaml and save
messages_all.dart will be generated with new Future.value

Via this route, none of the files are generated when saving an arb file
```

**System info**
<The output of `dart pub deps --style compact` in your project>

**Comment by mosuem** [comment]
I assume this is about the [Flutter intl](https://marketplace.visualstudio.com/items?itemName=localizely.flutter-intl) VS code plugin? Or how do you generate `messages_all.dart`?

**Comment by dgt-erik** [comment]
Hi Moritz,

Yes its about that plugin,
I think i posted it under the wrong Intl, sorry

With kind regards,

Erik Bozelie | DGT
Development
[https://attachments.office.net/owa/erik%40dgt.nl/service.svc/s/GetAttachmentThumbnail?id=AAMkAGVhNTJiNjkxLTc2MTktNGU4Mi04ZDAxLTVhYzAyOTM2M2E1YQBGAAAAAAB%2BsSeNRjHdQY%2Bc8ntRHsIgBwDK8muBnxTYRLVwGW%2B0D7IyAAAAAAEMAADK8muBnxTYRLVwGW%2B0D7IyAAAJL8IeAAABEgAQAGqiX6FqJJVOtpcfCMuy7zs%3D&thumbnailType=2&token=eyJhbGciOiJSUzI1NiIsImtpZCI6IkQ4OThGN0RDMjk2ODQ1MDk1RUUwREZGQ0MzODBBOTM5NjUwNDNFNjQiLCJ0eXAiOiJKV1QiLCJ4NXQiOiIySmozM0Nsb1JRbGU0Tl84dzRDcE9XVUVQbVEifQ.eyJvcmlnaW4iOiJodHRwczovL291dGxvb2sub2ZmaWNlLmNvbSIsInVjIjoiNzAyOWNlODkzOGVlNDI1NGFiZjZmZTgyYjAzZTRjMjQiLCJzaWduaW5fc3RhdGUiOiJbXCJrbXNpXCJdIiwidmVyIjoiRXhjaGFuZ2UuQ2FsbGJhY2suVjEiLCJhcHBjdHhzZW5kZXIiOiJPd2FEb3dubG9hZEBhMTQ5ZTQ0ZS03MDRmLTQ2YzctODI1ZS02OTRlZTIyNzQ0NzAiLCJpc3NyaW5nIjoiV1ciLCJhcHBjdHgiOiJ7XCJtc2V4Y2hwcm90XCI6XCJvd2FcIixcInB1aWRcIjpcIjExNTM4MDExMjE5OTgyNzY4NjJcIixcInNjb3BlXCI6XCJPd2FEb3dubG9hZFwiLFwib2lkXCI6XCI2NWQ3ODI2Yi0yNjlhLTQ0ODQtYmE0Mi03NDRhMWVjMmY4NjRcIixcInByaW1hcnlzaWRcIjpcIlMtMS01LTIxLTE4NzU2NTU3NjctMTI0OTkyMzczNC0zMjEwODk3NDYxLTgyNjc1NjhcIn0iLCJuYmYiOjE2NzI2NjY5NTgsImV4cCI6MTY3MjY2NzU1OCwiaXNzIjoiMDAwMDAwMDItMDAwMC0wZmYxLWNlMDAtMDAwMDAwMDAwMDAwQGExNDllNDRlLTcwNGYtNDZjNy04MjVlLTY5NGVlMjI3NDQ3MCIsImF1ZCI6IjAwMDAwMDAyLTAwMDAtMGZmMS1jZTAwLTAwMDAwMDAwMDAwMC9hdHRhY2htZW50cy5vZmZpY2UubmV0QGExNDllNDRlLTcwNGYtNDZjNy04MjVlLTY5NGVlMjI3NDQ3MCIsImhhcHAiOiJvd2EifQ.SB9BqsrT3dHf-rDun5vS05iwm8JC2PqhR6yEVJZIizPoL3onV5OOYuXuaow91H5MK70rAJlIdJk1Mlgvnh3CbUsXan60eWqjo2t4eiaGvxFk-kM0THn7Gf0lP294OVBVKFndhdTp-6a06i2jZIc2zbYG9o7lN2MvsXt3FCoi9PxOecxeUc6HWclUwK9h7cMz6nmPoihPH5QXZfz058e75VPlfJ5a4gIPMEBJ6gK23ONLlKiYE34gPsZZlFrs2d1b9nmHeEuBcr2NQilOg8oSl824LfaSni1Nb6NOv_6uvvBB5tAMPbObRp3jV-0cuDjsxiRTTMrWAJ2U7zYNuR0dTA&X-OWA-CANARY=cMurou4KV0672zUczRnjM1A5VUrH7NoYKuI-fJDiIouIx7U0b_AvLUV79G2ZsYULG4yvw3nnWQU.&owa=outlook.office.com&scriptVer=20221209009.13&animation=true]
digitalgametechnology.com
+31 (0)53 430 51 95

________________________________
