### ISSUE TITLE
Existing l10n.yaml file is mandatory or null check assertion is thrown in AppLocalizations.of

### ISSUE THREAD

**Issue by rjduffsep** [dart-lang/intl#550]
**Describe the bug**
Following [the documentation](https://docs.flutter.dev/development/accessibility-and-localization/internationalization) to install internationalization and localization **except not adding** the `l10n.yaml` file results in a null check assertion failure when localizations are attempted to be used to set a`MaterialApp.title` property. Otherwise sensible defaults allow translations to work in the rest of the app. None of the default properties (`arb-dir, template-arb-file, or output-localization-file`) of `l10n.yaml` seem to have anything to do with setting a null check assertion versus returning a nullable type.

**Expectations** 
Without a `l10n.yaml file` the `AppLocalizations` class file generated should still return a nullable type not throw a null check assertion exception. Or a **stronger** warning should be placed in the documented steps that broken behavior might occur without this file.

**To Reproduce**
Follow [guide here](https://docs.flutter.dev/development/accessibility-and-localization/internationalization#setting-up) to create a new project (`flutter create test`) and add internationalization.
Follow [guide here](https://docs.flutter.dev/development/accessibility-and-localization/internationalization#adding-your-own-localized-messages) to add localizations, but do not add a `l10n.yaml` file (Step 3).
Add `app_en.arb` localization file (Step 4) as described.
Run `flutter gen-l10n`
Modify `main.dart` as described.
Call `AppLocalizations.of` in MyHomePage, see `main.dart` code file below.
Run app and observe application runs with translated text.

Call `AppLocalizations.of` in MaterialApp title, see `main.dart` code file below.
Run app and observe application hits an exception of "Null check operator used on a null value" in the `of` method of the AppLocalizations class:
```
static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations)!;
}
```

Add the `l10n.yaml` as described in step 3 of the [localizations guide](https://docs.flutter.dev/development/accessibility-and-localization/internationalization#adding-your-own-localized-messages).
Run `flutter gen-l10n`
Observe that null assertion has disappeared from the `app_localizations.dart` file.
```
static AppLocalizations? of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations);
}
```

Run app and observe application runs with translated text again.

```
import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:flutter_gen/gen_l10n/app_localizations.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: AppLocalizations.of(context)?.helloWorld ?? '', // BREAKS IF l10n.yaml FILE NOT PROVIDED
      localizationsDelegates: const [
        AppLocalizations.delegate,
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
      ],
      supportedLocales: const [
        Locale('en'), // English
        Locale('es'), // Spanish
      ],
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title:
            Text(AppLocalizations.of(context)?.helloWorld.toUpperCase() ?? ''),
      ),
      body: Center(
          child: Text(
              AppLocalizations.of(context)?.helloWorld.toLowerCase() ?? '')),
    );
  }
}
```

**System info**
```
Dart SDK 2.19.1
Flutter SDK 3.7.1
test 1.0.0+1

dependencies:
- cupertino_icons 1.0.5
- flutter 0.0.0 [characters collection js material_color_utilities meta vector_math sky_engine]
- flutter_localizations 0.0.0 [flutter intl characters clock collection js material_color_utilities meta path vector_math]
- intl 0.17.0 [clock path]
- sky_engine 0.0.99
- source_span 1.9.1 [collection path term_glyph]
- stack_trace 1.11.0 [path]
- stream_channel 2.1.1 [async]- string_scanner 1.2.0 [source_span]
- term_glyph 1.2.1
- test_api 0.4.16 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]
- vector_math 2.1.4
```

**Comment by mosuem** [comment]
Please refile this in the Flutter repo, as this is not related to package:intl. Thanks!
