### ISSUE TITLE
Dateformat.parse seems to be returning wrong timing

### ISSUE THREAD

**Issue by Elemenopeee** [dart-lang/intl#557]
**Describe the bug**
I tried formatting "2023-03-01T06:10:28.608213Z" this date using 
DateFormat("yyyy-MM-dd'T'HH:mm:ss.SSS'Z'").parse("2023-03-01T06:10:28.608213Z").

I got back "2023-03-01 06:20:36:213"

**To Reproduce**
This happens with all dates, the Dateformat.parse seems to be adding about 10 minutes to the given time. 

**System info**
Using intl: ^0.17.0 as intl: ^0.18.0 is incompatible with awesome_notifications: ^0.7.4+1

Here is the link to that issue even if its a different issue -> https://github.com/rafaelsetragni/awesome_notifications/issues/735

**Comment by mosuem** [comment]
Thanks for filing this.

I suspect that the parser is adding 608213 "fractional seconds" to the time. As you specified `SSS`, this means milliseconds, which corresponds roughly to 10 minutes.

In general, the symbols such as `S` are not placeholders for numbers, but rather a skeleton. For a fixed DateTime pattern which is not supposed to be locale-specific, consider using [package:convert](https://pub.dev/documentation/convert/latest/convert/FixedDateTimeFormatter-class.html) instead.
