### ISSUE TITLE
../../.pub-cache/hosted/pub.dev/intl-0.17.0/lib/intl_browser.dart:12:8: Error: Dart library 'dart:html' is not available on this platform

### ISSUE THREAD

**Issue by mhd-arshad-cloudme** [dart-lang/intl#576]
i updated the package to 0.17.0 before it was running perfect
after updating i am not able to run app. on IOS 

this is the error i am getting.

Error (Xcode): ../../.pub-cache/hosted/pub.dev/intl-0.17.0/lib/intl_browser.dart:12:8: Error: Dart library 'dart:html' is not available on this platform.

Could not build the application for the simulator.
Error launching application on iPhone 14 Pro Max.

**Comment by mosuem** [comment]
Hi, are you trying to use dart:html in a native setting? Maybe `initializeDateFormatting` is the culprit here, please make sure to import from the right file (probably `date_symbol_data_local.dart` in your case, not `date_symbol_data_http_request.dart`).
