### ISSUE TITLE
Incorrect 12hour patterns in date_format.dart

### ISSUE THREAD

**Issue by piloopin** [dart-lang/intl#71]
12 hour pattern is small h which is incorrectly typed as small j. See https://github.com/dart-lang/intl/blob/2f5e9fa81d805fd0aa3426768d8da315d37fb0ec/lib/src/intl/date_format.dart#L419 for an example.

**Comment by alan-knight** [comment]
I'm not clear what you mean.

There is a skeleton for "j" and other variations which prints differently depending on the locale. "h" is not available as a skeleton, but always prints 12 hour. e.g.

```dart
import 'package:intl/intl.dart';
import 'package:intl/date_symbol_data_local.dart';

main() async {
  await initializeDateFormatting("en_US", null);
  printUS();
  await initializeDateFormatting("de_DE", null);
  printDE();
}

printUS() => Intl.withLocale("en_US", printDates);
printDE() => Intl.withLocale("de_DE", printDates);

printDates() {
  var j = new DateFormat.j();
  var h = new DateFormat("h");
  var H = new DateFormat.H();
  var now = new DateTime.now();
  print("j: "+ j.format(now));
  print("h: "+ h.format(now));
  print("H: " + H.format(now));
}
```

prints

```
j: 5 PM
h: 5
H: 17
j: 17 Uhr
h: 5
H: 17 Uhr
```

Note that since h is not a skeleton, it's directly a pattern. So if you write "jm" you'll get something like "4:22". If you write "hm" you'll get "422".

**Comment by piloopin** [comment]
Thanks for the clarification. I didn't know this is part of the unicode spec. I was mostly looking at ICU. imho this 'j' thing is a useful feature but a little bit non-intuitive since the character doesn't correspond to any word. Anyway, it would be nice if you fix the docs and add some explanation. (see https://github.com/dart-lang/intl/blob/2f5e9fa81d805fd0aa3426768d8da315d37fb0ec/lib/src/intl/date_format.dart#L115 for an example)

**Comment by alan-knight** [comment]
Some doc improvements in https://codereview.chromium.org//1232003005
