### ISSUE TITLE
Bad links to DateFormat docs in README.md

### ISSUE THREAD

**Issue by brianneal-wf** [dart-lang/intl#77]
There are at least two links to the documentation for DateFormat that are broken in README.md. The bad links point to:

https://api.dartlang.org/apidocs/channels/stable/dartdoc-viewer/intl/intl.DateFormat

I don't know if the problem is with the README.md or api.dartlang.org.

**Comment by alan-knight** [comment]
Fixed in c2b7d3d9c51c0c141ffe2f257c53eae9d21984f9
