### ISSUE TITLE
Intl.plural signature fails analyzer in strong mode

### ISSUE THREAD

**Issue by natebosch** [dart-lang/intl#78]
The examples for calling Intl.plural include the 'howMany' placeholder argument in the 'examples' argument, but examples is a Map<String, String> while howMany is an int. This produces an error from the analyzer in Strong mode which complains:
(Map<dynamic, dynamic>) is not of type Map<String, String> because 3 cannot be typed as String

The same thing happens when putting howMany in the args list:
(List<dynamic>) is not of type List<String> because howMany cannot be typed as String

**Comment by alan-knight** [comment]
This was fixed a long time ago.
