### ISSUE TITLE
Concatenated literal strings in message argument fails

### ISSUE THREAD

**Issue by alan-knight** [dart-lang/intl#79]
e.g. "Something too long" +
"to fit on one line"

We just say that the strings have to be literals. It's an easy workaround to just remove the "+", because adjacent literal strings are concatenated. But we should either accept the + or else produce a clear error message that says to just remove it.

**Comment by tijoforyou** [comment]
Ideally, we should accept the +.

Because, as per https://api.dartlang.org/133531/dart-core/String-class.html,
You can use the plus (+) operator to concatenate strings:

    'Dart ' + 'is ' + 'fun!'; // 'Dart is fun!'
You can also use adjacent string literals for concatenation:

    'Dart ' 'is ' 'fun!';    // 'Dart is fun!'

**Comment by alan-knight** [comment]
The strings in Intl messages are restricted. Even if we accepted + we're not going to accept
   'You have ' + number.toString() + 'messages.'
But if it's not difficult, I agree we might as well accept it for literals.

**Comment by tijoforyou** [comment]
Yes. We don't need to support strings like
`'You have ' + number.toString() + 'messages.'`
In this case, `number` should be made an argument, which is then interpolated.

We only need to accept string literals.

**Comment by alan-knight** [comment]
Fixed in 0.12.5-dev
