### ISSUE TITLE
Intl.select code generation error

### ISSUE THREAD

**Issue by slambour** [dart-lang/intl#8]
This code 

    String languages(String locale) => Intl.select(locale, 
       {
         "fr" : "frensh",
         "en" : "english"
        },
        name: "languages", 
        args: [locale]);

is generated by intl:generate_from_arb with in locale FR likes that :  

    static languages(locale) => "{locale, select, fr {Français } en {Anglais }}";    

When I use the default locale (en) it work well with this angulardart code

        <select class="form-control"  ng-model="localeSelected">
            <option ng-repeat="language in ownerProfile['languages']" value="{{language}}">{{intl.languages(language)}}</option>
        </select>

But with the fr locale the value `{locale, select, fr {Français } en {Anglais }}` is instead of `Français`

When I edit the generated intl_fr.dart generated file and replace 

      static languages(locale) => "{locale, select, fr {Français } en {Anglais }}";

by 

    static languages(locale) => {"fr":"Français","en":"Anglais"}[locale];

all works fine 
I don't understand why the behaviour is different between the default locale code and a selected locale

**Comment by alan-knight** [comment]
The default locale doesn't go through any of the translation machinery, it just returns the default string. And the generated code for FR does not look right at all. It should be generated Dart code that would return either Français or Anglais, not the ICU string.

What does your ARB look like, and where did you get it from? I note that if I run this through Google translate generate_from_arb crashes on the result. I think it doesn't like there being a "placeholder" that isn't actually used as a placeholder. I will investigate.

**Comment by alan-knight** [comment]
The ARB parser doesn't like spaces between the identifier and the text, i.e. it expects 
"en{Anglais}" rather than "en {Anglais}". Google translate toolkit is putting in the spaces now, so the parser needs to accept that.

Given that change, or taking the spaces out, your example behaves as I expect, which is to say that it throws and says you have to have a case for "other". And if I add that, then it works.

**Comment by alan-knight** [comment]
https://codereview.chromium.org/1151133002/

**Comment by alan-knight** [comment]
Published as 0.12.4

**Comment by slambour** [comment]
Works like a charm, thanks for your reactivity
