### ISSUE TITLE
DateFormat.parseLoose() incorrectly handles unexpected delimiters

### ISSUE THREAD

**Issue by cpelling** [dart-lang/intl#80]
``` dart
new DateFormat('yyyy-MM-dd').parseLoose("1/11"); // returns 0001-11-1
```

The above invocation of parseLoose() should fail with a FormatException, but instead returns November 1st, 1 A.D.

I've looked into this a little and have identified two contributing causes:
- When _DateFormatField.parseLiteralLoose() encounters an unexpected delimiter (such as a '/' instead of a '-'), it does nothing and allows parsing to continue. It should either throw a FormatException, or allow substitution of the delimiter but read past it.
- _Stream.nextInteger() skips leading punctuation and doesn't advance the stream far enough to account for this. It should either throw a FormatException if the stream does not start with a number, or advance the stream past the end of the number that is actually parsed.

**Comment by cpelling** [comment]
The following changes to [_DateFormatField.parseLiteralLoose()](https://github.com/dart-lang/intl/blob/1c2757633fb7a425a4ca48eb7902dbdf4960aa2c/lib/src/intl/date_format_field.dart#L61) appear to fix this issue and issue #81.

```dart
  void parseLiteralLoose(_Stream input) {
    var found = input.peek(width);
    var trimmedPattern = pattern.trim();
    if (found.startsWith(trimmedPattern)) {
      input.read(trimmedPattern.length);
      while (!input.atEnd() && input.peek().trim().isEmpty) {
        input.read();
      }
    } else {
      throwFormatException(input);
    }
  }
```

**Comment by alan-knight** [comment]
Unfortunately it makes other test cases fail, e.g. Sep 3 2014

Loose parsing in general makes me nervous with many different locales. For example, allowing no whitespace after delimiters seems reasonable enough. But what if the delimiter is space? I think we can handle that, and it seems good that an unknown delimiter should be a format exception, but I want to be careful we're not introducing other problems.

**Comment by cpelling** [comment]
It's definitely a tricky area. I'm not sure what we can really do about it other than introducing as many unit tests as possible (which I obviously neglected to run on my earlier proposal, sorry about that!)

In that spirit, here are some similar failure cases I just noticed. In each case, '0012-12-02' is returned instead of the expected FormatException.

      new DateFormat.yMMMd("ja").parseLoose('12月12日')
      new DateFormat.yMEd("ja").parseLoose('12月12日')
      new DateFormat.yMMMEd("ja").parseLoose('12月12日')
      new DateFormat.yMMMMd("ja").parseLoose('12月12日')
      new DateFormat.yMMMMEEEEd("ja").parseLoose('12月12日')

I'll try to find some time for looking at this properly soon.

**Comment by alan-knight** [comment]
Fixed in https://github.com/dart-lang/intl/commit/0c284428b4d2b97e944e29e9b5f2c5a5deea39af
