### ISSUE TITLE
Separate out code that relies on analyzer, args, etc – pkg/intl_util

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/intl#82]
Folks wanting the runtime features (like datetime parsing) shouldn't need to worry about analyzer version breaks, etc

**Comment by alan-knight** [comment]
You're suggesting to split it out into a separate package?

**Comment by kevmoo** [comment]
Yup. Angular only needs a small slice of intl – as do many packages.

Many folks could avoid depending on the whole thing – with it's tie-ins to analyzer, etc.

**Comment by alan-knight** [comment]
Done in 0.14.0
