### ISSUE TITLE
Provide a way of doing hard-coded server dates

### ISSUE THREAD

**Issue by alan-knight** [dart-lang/intl#83]
I keep seeing things where people want to use DateFormat for a fixed format used to communicate with another program. It's very slow for that, and people may not realize that the format can change with different locales until they test in an unusual one. Maybe it would be worthwhile to provide some kind of constructor like
   DateFormat.forServer(pattern)
where it create a different sort of format object that ignores the locale and is very limited with respect to the pattern. Basically only understands the letters y, m, and d, and only cares about how many digits you want for each, and does padding.

**Comment by ErikCorryGoogle** [comment]
Perhaps just omit the pattern and assume ISO8601 standard: 2007-04-05T14:30Z

**Comment by zoechi** [comment]
+1 for parsing exactly according to the specified format
The iso format can easily parsed with the `DateTime` class
```dart
DateTime.parse('2007-04-05T14:30Z')
```
[DartPad](https://dartpad.dartlang.org/9b34a413a77187a5ba8b)

**Comment by alan-knight** [comment]
It was also noted on another bug that DateTime.parse can handle the no-delimiter case, e.g. 20171224, which is another of the common ones.

**Comment by mosuem** [comment]
See #457 .
