### ISSUE TITLE
Generated library names won't pass linting with generate_from_arb

### ISSUE THREAD

**Issue by donny-dont** [dart-lang/intl#87]
Currently there's no way to specify the library name that generate_from_arb produces. This means if you run the linter against a generated library that it will fail.

The analyzer was relaxed to allow library names to be omitted so that's one option. Another option is to have a flag that allows the library name to be prefixed. A further option is to read the pubspec and get the library name from that and then based on the path determine the library name based on the conventions.

The flag is probably the most straightforward of those options.

**Comment by alan-knight** [comment]
So what is it that causes the linter to fail? My thought would be that the library name should match the file name, so there doesn't need to be an additional option, it should just use the generated-file-prefix. Or is there something else that's a problem? Or we could just omit the name, I think.

**Comment by donny-dont** [comment]
Currently to run one of my arb files I do the following command after a pub install.

`pub run intl:generate_from_arb --output-dir lib/src lib/intl.dart translations/en_GB.arb`

The generated file has the following header.

```
/**
 * DO NOT EDIT. This is code generated via package:intl/generate_localized.dart
 * This is a library that provides messages for a GB locale. All the
 * messages from the main program should be duplicated here with the same
 * function name.
 */

library messages_GB;
import 'package:intl/intl.dart';
import 'package:intl/message_lookup_by_library.dart';
```

If the package name is my_intl then the library name should be `my_intl.src.messages_gb` when following the convention. Not sure if it should be my problem to make the translation filename be all lower case but that's another bit of bad behavior.

**Comment by donny-dont** [comment]
Another lint issue I see here @alan-knight is that if you had

```
"msgFridayVariable":"Friday, {time}",
"@msgFridayVariable":{"type":"text","placeholders":{"time":{}}},
```

The generated code is

```
static msgFridayVariable(time) => "Friday, ${time}";
```

When it should be

```
static msgFridayVariable(time) => "Friday, $time";
```

Can probably do some kind of regex around that.

**Comment by dam0vm3nt** [comment]
There's also another point : if you have several libraries using `.arb` generated `locale` all of them will have the same name and conflicting.

To be honest I think this use case at the moment will apply only to me because I've patched the `CompositeMessageLookup` to allow for merging multiple messages (BTW this IMHO can be a feature request).

**Comment by alan-knight** [comment]
I filed https://github.com/dart-lang/linter/issues/165 , but the feeling there seems to be to use .analysis_options to exclude the generated code. But I'll remove the library directive anyway, I don't think it's serving any real purpose.

I'm not sure if excluding the files from analysis really works - would it mean that calls to initializeMessages would show as errors?

I think multiple independent libraries is a separate issue.

**Comment by bwilkerson** [comment]
> I'm not sure if excluding the files from analysis really works ...

It *is* kind of confusing. When you exclude files from analysis it's really saying "don't analyze these files unless you need to, and even then treat them as if they were external to my package" (similar to the way code from other packages is treated).

**Comment by alan-knight** [comment]
For the library name it's probably simplest to remove it. I don't think it's used for anything. Trying to figure out the name from the path seems poor. And what is it supposed to do when the library isn't in a package URL accessible location, either because it's not in a package at all, or it's in somewhere like /test.

It's probably excessive paranoia from too much dealing with XSS and SQL injection, but I prefer putting the ${} around names that are being added programmatically.

Library name removed in 0.12.6.

**Comment by marcelgarus** [comment]
Is there any harm in adding the following comment at the top of the generated file, as suggested in [a related issue in the linter](https://github.com/dart-lang/linter/issues/165)?
```
// ignore_for_file: non_constant_identifier_names, omit_local_variable_types, unnecessary_brace_in_string_interps
```
