### ISSUE TITLE
Doc link broken in README.md

### ISSUE THREAD

**Issue by eseidelGoogle** [dart-lang/intl#92]
https://pub.dartlang.org/packages/intl

In the "Date Formatting and Parsing" section, the DateFormat link:
https://api.dartlang.org/apidocs/channels/stable/dartdoc-viewer/intl/intl.DateFormat

is broken.  Happy to fix it, but I don't know where the right link goes.
https://github.com/dart-lang/intl/blame/master/README.md#L255 is the line in question.

**Comment by eseidelGoogle** [comment]
@sethladd might know who to ask.

**Comment by sethladd** [comment]
https://www.dartdocs.org/documentation/intl/latest/intl/DateFormat-class.html is the link to use.

Thanks for pointing this out!
