### ISSUE TITLE
Add a parameter to `generate_from_arb` to customize the generated library name

### ISSUE THREAD

**Issue by dam0vm3nt** [dart-lang/intl#96]
Currently the generated library name is of the form `messages_${localeName}`. 
In a scenario where one project has several dependency libraries each carrying their own generated files you end up having duplicated library names that is annoying.

It would be nice to have a way to change the generated library name in the same way it is possible to add a prefix to the generated files.

**Comment by zoechi** [comment]
#87 seems related

**Comment by dam0vm3nt** [comment]
definitively. even with a slight different use case.

**Comment by alan-knight** [comment]
This seems like it's addressed by the --generated-file-prefix option.
