### ISSUE TITLE
Add support for JS localeCompare operation

### ISSUE THREAD

**Issue by alan-knight** [dart-lang/intl#97]
We don't want to try and provide collation support ourselves, it's very large, but might reasonably provide a call-through to the JS String.localeCompare operation. Some questions about where to put it, and what to do in a non-JS context. Would it make sense to provide it in dart:html or similar library instead?

**Comment by tonosama-atlacatl** [comment]
+1
👍 , I REALLY needed this last week... it would be nice to simply call ".localeCompare" than the crazy lowercasing and compareTo..

**Comment by alan-knight** [comment]
This is really a duplicate of #2
